<?php

use Illuminate\Database\Seeder;

class NESSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$games = [
			["10-Yard Fight", 1985, "Nintendo", 'NA'],
			["1942", 1986, "Capcom", 'NA'],
			["1943: The Battle of Midway", 1988, "Capcom", 'NA'],
			["3-D WorldRunner", 1987, "Acclaim", 'NA'],
			["720°", 1989, "Mindscape", 'NA'],
			["8 Eyes", 1990, "Taxan", 'NA'],
			["Abadox", 1990, "Milton Bradley", 'NA'],
			["Addams Family, The", 1992, "Ocean Software", 'NA'],
			["Addams Family, The: Pugsley's Scavenger Hunt", 1993, "Ocean Software", 'NA'],
			["Advanced Dungeons & Dragons: DragonStrike", 1992, "FCI", 'NA'],
			["Advanced Dungeons & Dragons: Heroes of the Lance", 1991, "FCI", 'NA'],
			["Advanced Dungeons & Dragons: Hillsfar", 1993, "FCI", 'NA'],
			["Advanced Dungeons & Dragons: Pool of Radiance", 1992, "FCI", 'NA'],
			["Adventure Island", 1988, "Hudson Soft", 'NA'],
			["Adventure Island 3", 1992, "Hudson Soft", 'NA'],
			["Adventure Island II", 1991, "Hudson Soft", 'NA'],
			["Adventures in the Magic Kingdom", 1990, "Capcom", 'NA'],
			["Adventures of Bayou Billy, The", 1989, "Konami", 'NA'],
			["Adventures of Dino Riki", 1989, "Hudson Soft", 'NA'],
			["Adventures of Gilligan's Island, The", 1990, "Bandai", 'NA'],
			["Adventures of Lolo", 1989, "HAL Laboratory", 'NA'],
			["Adventures of Lolo 2", 1990, "HAL Laboratory", 'NA'],
			["Adventures of Lolo 3", 1991, "HAL Laboratory", 'NA'],
			["Adventures of Rad Gravity, The", 1990, "Activision", 'NA'],
			["Adventures of Rocky and Bullwinkle and Friends, The", 1992, "THQ", 'NA'],
			["Adventures of Tom Saywer, The", 1989, "Meldac", 'NA'],
			["Air Fortress", 1989, "HAL Laboratory", 'NA'],
			["Airwolf", 1989, "Acclaim", 'NA'],
			["Al Unser Jr. Turbo Racing", 1990, "Data East", 'NA'],
			["Alfred Chicken", 1994, "Mindscape", 'NA'],
			["Alien 3", 1993, "LJN", 'NA'],
			["All-Pro Basketball", 1989, "Vic Tokai", 'NA'],
			["Alpha Mission", 1987, "SNK", 'NA'],
			["Amagon", 1989, "American Sammy", 'NA'],
			["American Gladiators", 1991, "GameTek", 'NA'],
			["Anticipation", 1988, "Nintendo", 'NA'],
			["Arch Rivals", 1990, "Acclaim", 'NA'],
			["Archon", 1989, "Activision", 'NA'],
			["Arkanoid", 1987, "Taito", 'NA'],
			["Arkista's Ring", 1990, "American Sammy", 'NA'],
			["Astyanax", 1990, "Jaleco", 'NA'],
			["Athena", 1987, "SNK", 'NA'],
			["Athletic World (Family Fun Fitness label)", 1987, "Bandai", 'NA'],
			["Athletic World (Power Pad label)", 1988, "Bandai", 'NA'],
			["Attack of the Killer Tomatoes", 1992, "THQ", 'NA'],
			["Back to the Future", 1989, "LJN", 'NA'],
			["Back to the Future Part II & III", 1990, "LJN", 'NA'],
			["Bad Dudes", 1990, "Data East", 'NA'],
			["Bad News Baseball", 1990, "Tecmo", 'NA'],
			["Bad Street Brawler", 1989, "Mattel Electronics", 'NA'],
			["Balloon Fight", 1986, "Nintendo", 'NA'],
			["Bandai Golf: Challenge Pebble Beach", 1989, "Bandai", 'NA'],
			["Bandit Kings of Ancient China", 1990, "Koei", 'NA'],
			["Barbie", 1991, "Hi-Tech Expressions", 'NA'],
			["Bard's Tale, The", 1991, "FCI", 'NA'],
			["Barker Bill's Trick Shooting", 1990, "Nintendo", 'NA'],
			["Baseball", 1985, "Nintendo", 'NA'],
			["Baseball Simulator 1.000", 1990, "Culture Brain", 'NA'],
			["Baseball Stars", 1989, "SNK", 'NA'],
			["Baseball Stars II", 1992, "Romstar", 'NA'],
			["Bases Loaded", 1988, "Jaleco", 'NA'],
			["Bases Loaded 3", 1991, "Jaleco", 'NA'],
			["Bases Loaded 4", 1993, "Jaleco", 'NA'],
			["Bases Loaded II: Second Season", 1990, "Jaleco", 'NA'],
			["Batman", 1990, "Sunsoft", 'NA'],
			["Batman Returns", 1993, "Konami", 'NA'],
			["Batman: Return of the Joker", 1991, "Sunsoft", 'NA'],
			["Battle Chess", 1990, "Data East", 'NA'],
			["Battle of Olympus, The", 1989, "Broderbund", 'NA'],
			["Battle Tank", 1990, "Absolute", 'NA'],
			["Battleship", 1993, "Mindscape", 'NA'],
			["Battletoads", 1991, "Tradewest", 'NA'],
			["Battletoads & Double Dragon", 1993, "Tradewest", 'NA'],
			["Beetlejuice", 1991, "LJN", 'NA'],
			["Best of the Best: Championship Karate", 1992, "Electro Brain", 'NA'],
			["Bigfoot", 1990, "Acclaim", 'NA'],
			["Bill & Ted's Excellent Video Game Adventure", 1991, "LJN", 'NA'],
			["Bill Elliott's NASCAR Challenge", 1991, "Konami", 'NA'],
			["Bionic Commando", 1988, "Capcom", 'NA'],
			["Black Bass, The", 1989, "Hot-B", 'NA'],
			["Blades of Steel (original -- silver label)", 1988, "Konami", 'NA'],
			["Blades of Steel (reissue -- red label)", 1990, "Konami", 'NA'],
			["Blaster Master", 1988, "Sunsoft", 'NA'],
			["Blue Marlin, The", 1992, "Hot-B", 'NA'],
			["Blues Brothers, The", 1992, "Titus", 'NA'],
			["Bo Jackson Baseball", 1991, "Data East", 'NA'],
			["Bomberman", 1987, "Hudson Soft", 'NA'],
			["Bomberman II", 1993, "Hudson Soft", 'NA'],
			["Bonk's Adventure", 1994, "Hudson Soft", 'NA'],
			["Boulder Dash", 1990, "JVC", 'NA'],
			["Boy and His Blob, A: Trouble on Blobolonia", 1990, "Absolute", 'NA'],
			["Bram Stoker's Dracula", 1993, "Sony Imagesoft", 'NA'],
			["Break Time: The National Pool Tour", 1993, "FCI", 'NA'],
			["BreakThru", 1987, "Data East", 'NA'],
			["Bubble Bobble", 1988, "Taito", 'NA'],
			["Bubble Bobble Part 2", 1993, "Taito", 'NA'],
			["Bucky O'Hare", 1992, "Konami", 'NA'],
			["Bugs Bunny Birthday Blowout, The", 1990, "Kemco", 'NA'],
			["Bugs Bunny Crazy Castle, The", 1989, "Kemco", 'NA'],
			["Bump 'n' Jump", 1988, "Vic Tokai", 'NA'],
			["Burai Fighter", 1990, "Taxan", 'NA'],
			["BurgerTime", 1987, "Data East", 'NA'],
			["Cabal", 1990, "Milton Bradley", 'NA'],
			["Caesars Palace", 1992, "Virgin Games", 'NA'],
			["California Games", 1989, "Milton Bradley", 'NA'],
			["Captain America and the Avengers", 1991, "Data East", 'NA'],
			["Captain Planet and the Planeteers", 1991, "Mindscape", 'NA'],
			["Captain Skyhawk", 1990, "Milton Bradley", 'NA'],
			["Casino Kid", 1989, "Sofel", 'NA'],
			["Casino Kid II", 1993, "Sofel", 'NA'],
			["Castelian", 1991, "Triffix", 'NA'],
			["Castle of Dragon", 1990, "Seta", 'NA'],
			["Castlequest", 1989, "Nexoft", 'NA'],
			["Castlevania", 1987, "Konami", 'NA'],
			["Castlevania II: Simon's Quest", 1988, "Konami", 'NA'],
			["Castlevania III: Dracula's Curse", 1990, "Konami", 'NA'],
			["Caveman Games", 1990, "Data East", 'NA'],
			["Championship Bowling", 1989, "Romstar", 'NA'],
			["Championship Pool", 1993, "Mindscape", 'NA'],
			["Chessmaster, The", 1990, "Hi-Tech Expressions", 'NA'],
			["Chip 'n Dale: Rescue Rangers", 1990, "Capcom", 'NA'],
			["Chip 'n Dale: Rescue Rangers 2", 1994, "Capcom", 'NA'],
			["Chubby Cherub", 1986, "Bandai", 'NA'],
			["Circus Caper", 1990, "Toho", 'NA'],
			["City Connection", 1988, "Jaleco", 'NA'],
			["Clash at Demonhead", 1990, "Vic Tokai", 'NA'],
			["Classic Concentration", 1990, "GameTek", 'NA'],
			["Cliffhanger", 1993, "Sony Imagesoft", 'NA'],
			["Clu Clu Land", 1985, "Nintendo", 'NA'],
			["Cobra Command", 1988, "Data East", 'NA'],
			["Cobra Triangle", 1989, "Nintendo", 'NA'],
			["Code Name: Viper", 1990, "Capcom", 'NA'],
			["Color a Dinosaur", 1993, "Virgin Games", 'NA'],
			["Commando", 1986, "Capcom", 'NA'],
			["Conan: The Mysteries of Time", 1991, "Mindscape", 'NA'],
			["Conflict", 1990, "Vic Tokai", 'NA'],
			["Conquest of the Crystal Palace", 1990, "Asmik", 'NA'],
			["Contra", 1988, "Konami", 'NA'],
			["Contra Force", 1992, "Konami", 'NA'],
			["Cool World", 1993, "Ocean Software", 'NA'],
			["Cowboy Kid", 1992, "Romstar", 'NA'],
			["Crash 'n the Boys: Street Challenge", 1992, "American Technos", 'NA'],
			["Crystalis", 1990, "SNK", 'NA'],
			["Cyberball", 1992, "Jaleco", 'NA'],
			["Cybernoid: The Fighting Machine", 1989, "Acclaim", 'NA'],
			["CyberStadium Series: Base Wars", 1991, "Ultra Games (Konami)", 'NA'],
			["Dance Aerobics", 1989, "Nintendo", 'NA'],
			["Danny Sullivan's Indy Heat", 1992, "Tradewest", 'NA'],
			["Darkman", 1991, "Ocean Software", 'NA'],
			["Darkwing Duck", 1992, "Capcom", 'NA'],
			["Dash Galaxy in the Alien Asylum", 1990, "Data East", 'NA'],
			["Day Dreamin' Davey", 1992, "HAL Laboratory", 'NA'],
			["Days of Thunder", 1990, "Mindscape", 'NA'],
			["Deadly Towers", 1987, "Broderbund", 'NA'],
			["Defender II", 1988, "HAL Laboratory", 'NA'],
			["Defender of the Crown", 1989, "Ultra Games (Konami)", 'NA'],
			["Defenders of Dynatron City", 1992, "JVC", 'NA'],
			["Deja Vu", 1990, "Kemco", 'NA'],
			["Demon Sword", 1990, "Taito", 'NA'],
			["Desert Commander", 1989, "Kemco", 'NA'],
			["Destination Earthstar", 1990, "Acclaim", 'NA'],
			["Destiny of an Emperor", 1990, "Capcom", 'NA'],
			["Dick Tracy", 1990, "Bandai", 'NA'],
			["Die Hard", 1992, "Activision", 'NA'],
			["Dig Dug II", 1989, "Bandai", 'NA'],
			["Digger T. Rock: The Legend of the Lost City", 1990, "Milton Bradley", 'NA'],
			["Dirty Harry", 1990, "Mindscape", 'NA'],
			["Donkey Kong", 1986, "Nintendo", 'NA'],
			["Donkey Kong 3", 1986, "Nintendo", 'NA'],
			["Donkey Kong Classics", 1988, "Nintendo", 'NA'],
			["Donkey Kong Jr.", 1986, "Nintendo", 'NA'],
			["Donkey Kong Jr. Math", 1985, "Nintendo", 'NA'],
			["Double Dare", 1990, "GameTek", 'NA'],
			["Double Dragon", 1988, "Tradewest", 'NA'],
			["Double Dragon II: The Revenge", 1990, "Acclaim", 'NA'],
			["Double Dragon III: The Sacred Stones", 1991, "Acclaim", 'NA'],
			["Double Dribble", 1987, "Konami", 'NA'],
			["Dr. Chaos", 1988, "FCI", 'NA'],
			["Dr. Jekyll and Mr. Hyde", 1989, "Bandai", 'NA'],
			["Dr. Mario", 1990, "Nintendo", 'NA'],
			["Dragon Fighter", 1992, "Sofel", 'NA'],
			["Dragon Power", 1988, "Bandai", 'NA'],
			["Dragon Spirit: The New Legend", 1990, "Bandai", 'NA'],
			["Dragon Warrior", 1989, "Nintendo", 'NA'],
			["Dragon Warrior II", 1990, "Enix", 'NA'],
			["Dragon Warrior III", 1991, "Enix", 'NA'],
			["Dragon Warrior IV", 1992, "Enix", 'NA'],
			["Dragon's Lair", 1990, "Sony Imagesoft", 'NA'],
			["Duck Hunt", 1985, "Nintendo", 'NA'],
			["DuckTales", 1989, "Capcom", 'NA'],
			["DuckTales 2", 1993, "Capcom", 'NA'],
			["Dungeon Magic: Sword of the Elements", 1990, "Taito", 'NA'],
			["Dusty Diamond's All-Star Softball", 1990, "Broderbund", 'NA'],
			["Dynowarz: Destruction of Spondylus", 1990, "Bandai", 'NA'],
			["Elevator Action", 1987, "Taito", 'NA'],
			["Eliminator Boat Duel", 1991, "Electro Brain", 'NA'],
			["Excitebike", 1985, "Nintendo", 'NA'],
			["F-117A Stealth Fighter", 1992, "MicroProse", 'NA'],
			["F-15 Strike Eagle", 1992, "MicroProse", 'NA'],
			["Family Feud", 1991, "GameTek", 'NA'],
			["Faria: A World of Mystery & Danger!", 1991, "Nexoft", 'NA'],
			["Faxanadu", 1989, "Nintendo", 'NA'],
			["Felix the Cat", 1992, "Hudson Soft", 'NA'],
			["Ferrari Grand Prix Challenge", 1992, "Acclaim", 'NA'],
			["Fester's Quest", 1989, "Sunsoft", 'NA'],
			["Final Fantasy", 1990, "Nintendo", 'NA'],
			["Fire 'N Ice", 1993, "Tecmo", 'NA'],
			["Fisher Price: Firehouse Rescue", 1992, "GameTek", 'NA'],
			["Fisher Price: I Can Remember", 1990, "GameTek", 'NA'],
			["Fisher Price: Perfect Fit", 1990, "GameTek", 'NA'],
			["Fist of the North Star", 1989, "Taxan", 'NA'],
			["Flight of the Intruder", 1991, "Mindscape", 'NA'],
			["Flintstones, The: The Rescue of Dino & Hoppy", 1991, "Taito", 'NA'],
			["Flintstones, The: The Surprise at Dinosaur Peak!", 1994, "Taito", 'NA'],
			["Flying Dragon: The Secret Scroll", 1989, "Culture Brain", 'NA'],
			["Flying Warriors", 1991, "Culture Brain", 'NA'],
			["Formula One: Built to Win", 1990, "Seta", 'NA'],
			["Frankenstein: The Monster Returns", 1991, "Bandai", 'NA'],
			["Freedom Force", 1988, "Sunsoft", 'NA'],
			["Friday the 13th", 1989, "LJN", 'NA'],
			["Fun House", 1991, "Hi-Tech Expressions", 'NA'],
			["G.I. Joe: A Real American Hero", 1991, "Taxan", 'NA'],
			["G.I. Joe: The Atlantis Factor", 1992, "Capcom", 'NA'],
			["Galaga: Demons of Death", 1988, "Bandai", 'NA'],
			["Galaxy 5000", 1991, "Activision", 'NA'],
			["Gargoyle's Quest II: The Demon Darkness", 1992, "Capcom", 'NA'],
			["Gauntlet (licensed grey cart)", 1987, "Tengen", 'NA'],
			["Gauntlet II", 1990, "Mindscape", 'NA'],
			["Gemfire", 1992, "Koei", 'NA'],
			["Genghis Khan", 1990, "Koei", 'NA'],
			["George Foreman's KO Boxing", 1992, "Acclaim", 'NA'],
			["Ghost Lion", 1992, "Kemco", 'NA'],
			["Ghostbusters", 1988, "Activision", 'NA'],
			["Ghostbusters II", 1990, "Activision", 'NA'],
			["Ghosts 'n Goblins", 1986, "Capcom", 'NA'],
			["Ghoul School", 1992, "Electro Brain", 'NA'],
			["Goal!", 1989, "Jaleco", 'NA'],
			["Goal! Two", 1992, "Jaleco", 'NA'],
			["Godzilla 2: War of the Monsters", 1992, "Toho", 'NA'],
			["Godzilla: Monster of Monsters!", 1989, "Toho", 'NA'],
			["Gold Medal Challenge '92", 1992, "Capcom", 'NA'],
			["Golf", 1985, "Nintendo", 'NA'],
			["Golf Grand Slam", 1991, "Atlus", 'NA'],
			["Golgo 13: Top Secret Episode", 1988, "Vic Tokai", 'NA'],
			["Goonies II, The", 1987, "Konami", 'NA'],
			["Gotcha! The Sport!", 1987, "LJN", 'NA'],
			["Gradius", 1986, "Konami", 'NA'],
			["Great Waldo Search, The", 1992, "THQ", 'NA'],
			["Greg Norman's Golf Power", 1992, "Virgin Games", 'NA'],
			["Gremlins 2: The New Batch", 1990, "Sunsoft", 'NA'],
			["Guardian Legend, The", 1989, "Broderbund", 'NA'],
			["Guerrilla War", 1989, "SNK", 'NA'],
			["Gumshoe", 1986, "Nintendo", 'NA'],
			["Gun-Nac", 1991, "ASCII", 'NA'],
			["Gun.Smoke (gunslinger label)", 1988, "Capcom", 'NA'],
			["Gun.Smoke (silhouette label)", 1988, "Capcom", 'NA'],
			["Gyromite", 1985, "Nintendo", 'NA'],
			["Gyruss", 1989, "Ultra Games (Konami)", 'NA'],
			["Harlem Globetrotters", 1991, "GameTek", 'NA'],
			["Hatris", 1992, "Bullet Proof Software", 'NA'],
			["Heavy Barrel", 1990, "Data East", 'NA'],
			["Heavy Shreddin'", 1990, "Parker Brothers", 'NA'],
			["High Speed", 1991, "Tradewest", 'NA'],
			["Hogan's Alley", 1985, "Nintendo", 'NA'],
			["Hollywood Squares", 1989, "GameTek", 'NA'],
			["Home Alone", 1991, "THQ", 'NA'],
			["Home Alone 2: Lost in New York", 1992, "THQ", 'NA'],
			["Hook", 1992, "Sony Imagesoft", 'NA'],
			["Hoops", 1989, "Jaleco", 'NA'],
			["Hudson Hawk", 1992, "Sony Imagesoft", 'NA'],
			["Hunt for Red October, The", 1991, "Hi-Tech Expressions", 'NA'],
			["Hydlide", 1989, "FCI", 'NA'],
			["Ice Climber", 1985, "Nintendo", 'NA'],
			["Ice Hockey", 1988, "Nintendo", 'NA'],
			["Ikari III: The Rescue", 1991, "SNK", 'NA'],
			["Ikari Warriors", 1987, "SNK", 'NA'],
			["Ikari Warriors II: Victory Road", 1988, "SNK", 'NA'],
			["Image Fight", 1990, "Irem", 'NA'],
			["Immortal, The", 1990, "Electronic Arts", 'NA'],
			["Incredible Crash Dummies, The", 1994, "LJN", 'NA'],
			["Indiana Jones and the Last Crusade (Taito)", 1991, "Taito", 'NA'],
			["Indiana Jones and the Last Crusade (Ubisoft)", 1993, "Ubisoft", 'NA'],
			["Indiana Jones and the Temple of Doom (Mindscape)", 1988, "Mindscape", 'NA'],
			["Infiltrator", 1990, "Mindscape", 'NA'],
			["Iron Tank", 1988, "SNK", 'NA'],
			["Ironsword: Wizards & Warriors II", 1989, "Acclaim", 'NA'],
			["Isolated Warrior", 1991, "NTVIC", 'NA'],
			["Ivan 'Ironman' Stewart's Super Off Road", 1990, "Tradewest", 'NA'],
			["Jack Nicklaus' Greatest 18 Holes of Major Championship Golf", 1990, "Konami", 'NA'],
			["Jackal", 1988, "Konami", 'NA'],
			["Jackie Chan's Action Kung Fu", 1990, "Hudson Soft", 'NA'],
			["James Bond Jr.", 1992, "THQ", 'NA'],
			["Jaws", 1987, "LJN", 'NA'],
			["Jeopardy!", 1988, "GameTek", 'NA'],
			["Jeopardy! 25th Anniversary Edition", 1990, "GameTek", 'NA'],
			["Jeopardy! Junior Edition", 1989, "GameTek", 'NA'],
			["Jetsons, The: Cogswell's Caper!", 1992, "Taito", 'NA'],
			["Jimmy Connors Tennis", 1993, "Ubisoft", 'NA'],
			["Joe & Mac", 1992, "Data East", 'NA'],
			["John Elway's Quarterback", 1989, "Tradewest", 'NA'],
			["Jordan vs. Bird: One on One", 1989, "Milton Bradley", 'NA'],
			["Journey to Silius", 1990, "Sunsoft", 'NA'],
			["Joust", 1988, "HAL Laboratory", 'NA'],
			["Jungle Book, The", 1994, "Virgin Games", 'NA'],
			["Jurassic Park", 1993, "Ocean Software", 'NA'],
			["Kabuki Quantum Fighter", 1991, "HAL Laboratory", 'NA'],
			["Karate Champ", 1986, "Data East", 'NA'],
			["Karate Kid, The", 1987, "LJN", 'NA'],
			["Karnov", 1988, "Data East", 'NA'],
			["Kick Master", 1992, "Taito", 'NA'],
			["Kickle Cubicle", 1990, "Irem", 'NA'],
			["Kid Icarus", 1987, "Nintendo", 'NA'],
			["Kid Klown in Night Mayor World", 1993, "Kemco", 'NA'],
			["Kid Kool", 1990, "Vic Tokai", 'NA'],
			["Kid Niki: Radical Ninja", 1987, "Data East", 'NA'],
			["King's Knight", 1989, "Square", 'NA'],
			["Kings of the Beach", 1990, "Ultra Games (Konami)", 'NA'],
			["Kings Quest V", 1992, "Konami", 'NA'],
			["Kirby's Adventure", 1993, "Nintendo", 'NA'],
			["Kiwi Kraze", 1991, "Taito", 'NA'],
			["KlashBall", 1991, "Sofel", 'NA'],
			["Knight Rider", 1989, "Acclaim", 'NA'],
			["Krion Conquest, The", 1991, "Vic Tokai", 'NA'],
			["Krusty's Fun House", 1992, "Acclaim", 'NA'],
			["Kung Fu", 1985, "Nintendo", 'NA'],
			["Kung-Fu Heroes", 1989, "Culture Brain", 'NA'],
			["L'Empereur", 1991, "Koei", 'NA'],
			["Laser Invasion", 1991, "Konami", 'NA'],
			["Last Action Hero", 1993, "Sony Imagesoft", 'NA'],
			["Last Ninja, The", 1991, "Jaleco", 'NA'],
			["Last Starfighter, The", 1990, "Mindscape", 'NA'],
			["Lee Trevino's Fighting Golf", 1988, "SNK", 'NA'],
			["Legacy of the Wizard", 1989, "Broderbund", 'NA'],
			["Legend of Kage, The", 1987, "Taito", 'NA'],
			["Legend of Zelda, The (original -- gold cartridge)", 1987, "Nintendo", 'NA'],
			["Legend of Zelda, The (reissue -- grey cartridge)", 1992, "Nintendo", 'NA'],
			["Legendary Wings", 1988, "Capcom", 'NA'],
			["Legends of the Diamond", 1992, "Bandai", 'NA'],
			["Lemmings", 1992, "Sunsoft", 'NA'],
			["Lethal Weapon", 1993, "Ocean Software", 'NA'],
			["Life Force", 1988, "Konami", 'NA'],
			["Little League Baseball: Championship Series", 1990, "SNK", 'NA'],
			["Little Mermaid, The", 1991, "Capcom", 'NA'],
			["Little Nemo: The Dream Master", 1990, "Capcom", 'NA'],
			["Little Ninja Brothers", 1990, "Culture Brain", 'NA'],
			["Little Samson", 1992, "Taito", 'NA'],
			["Lode Runner", 1987, "Broderbund", 'NA'],
			["Lone Ranger, The", 1991, "Konami", 'NA'],
			["Loopz", 1990, "Mindscape", 'NA'],
			["Low G Man: The Low Gravity Man", 1990, "Taxan", 'NA'],
			["Lunar Pool", 1987, "FCI", 'NA'],
			["M.C. Kids", 1992, "Virgin Games", 'NA'],
			["M.U.L.E.", 1990, "Mindscape", 'NA'],
			["M.U.S.C.L.E.", 1986, "Bandai", 'NA'],
			["Mach Rider", 1985, "Nintendo", 'NA'],
			["Mad Max", 1990, "Mindscape", 'NA'],
			["Mafat Conspiracy, The", 1990, "Vic Tokai", 'NA'],
			["Magic Darts", 1991, "Romstar", 'NA'],
			["Magic Johnson's Fast Break", 1990, "Tradewest", 'NA'],
			["Magic of Scheherazade, The", 1989, "Culture Brain", 'NA'],
			["Magician", 1991, "Taxan", 'NA'],
			["Magmax", 1988, "FCI", 'NA'],
			["Major League Baseball", 1988, "LJN", 'NA'],
			["Maniac Mansion", 1990, "Jaleco", 'NA'],
			["Mappy-Land", 1989, "Taxan", 'NA'],
			["Marble Madness", 1989, "Milton Bradley", 'NA'],
			["Mario Bros.", 1986, "Nintendo", 'NA'],
			["Mario Is Missing!", 1993, "Mindscape", 'NA'],
			["Mario's Time Machine", 1994, "Mindscape", 'NA'],
			["Mechanized Attack", 1990, "SNK", 'NA'],
			["Mega Man", 1987, "Capcom", 'NA'],
			["Mega Man 2", 1989, "Capcom", 'NA'],
			["Mega Man 3", 1990, "Capcom", 'NA'],
			["Mega Man 4", 1992, "Capcom", 'NA'],
			["Mega Man 5", 1992, "Capcom", 'NA'],
			["Mega Man 6", 1994, "Nintendo", 'NA'],
			["Mendel Palace", 1990, "Hudson Soft", 'NA'],
			["Metal Gear", 1988, "Ultra Games (Konami)", 'NA'],
			["Metal Mech", 1991, "Jaleco", 'NA'],
			["Metal Storm", 1991, "Irem", 'NA'],
			["Metroid (original -- silver label)", 1987, "Nintendo", 'NA'],
			["Metroid (reissue -- yellow label)", 1992, "Nintendo", 'NA'],
			["Michael Andretti's World GP", 1990, "American Sammy", 'NA'],
			["Mickey Mousecapade", 1988, "Capcom", 'NA'],
			["Mickey's Adventure in Numberland", 1994, "Hi-Tech Expressions", 'NA'],
			["Mickey's Safari in Letterland", 1993, "Hi-Tech Expressions", 'NA'],
			["Might & Magic: Secret of the Inner Sanctum", 1992, "American Sammy", 'NA'],
			["Mighty Bomb Jack", 1987, "Tecmo", 'NA'],
			["Mighty Final Fight", 1993, "Capcom", 'NA'],
			["Mike Tyson's Punch-Out!!", 1987, "Nintendo", 'NA'],
			["Millipede", 1988, "HAL Laboratory", 'NA'],
			["Milon's Secret Castle", 1988, "Hudson Soft", 'NA'],
			["Miracle Piano Teaching System, The", 1990, "Mindscape", 'NA'],
			["Mission: Impossible", 1990, "Ultra Games (Konami)", 'NA'],
			["Monopoly", 1991, "Parker Brothers", 'NA'],
			["Monster in My Pocket", 1992, "Konami", 'NA'],
			["Monster Party", 1989, "Bandai", 'NA'],
			["Monster Truck Rally", 1991, "INTV", 'NA'],
			["Motor City Patrol", 1992, "Matchbox International", 'NA'],
			["Ms. Pac-Man (Namco)", 1993, "Namco", 'NA'],
			["Muppet Adventure: Chaos at the Carnival", 1990, "Hi-Tech Expressions", 'NA'],
			["Mutant Virus, The: Crisis in a Computer World", 1992, "American Softworks", 'NA'],
			["Mystery Quest", 1989, "Taxan", 'NA'],
			["NARC", 1990, "Acclaim", 'NA'],
			["NES Open Tournament Golf", 1991, "Nintendo", 'NA'],
			["NES Play Action Football", 1990, "Nintendo", 'NA'],
			["NFL Football", 1989, "LJN", 'NA'],
			["Nigel Mansell's World Championship Racing", 1993, "GameTek", 'NA'],
			["Nightmare on Elm Street, A", 1990, "LJN", 'NA'],
			["Nightshade", 1992, "Ultra Games (Konami)", 'NA'],
			["Ninja Crusaders", 1990, "American Sammy", 'NA'],
			["Ninja Gaiden", 1989, "Tecmo", 'NA'],
			["Ninja Gaiden II: The Dark Sword of Chaos", 1990, "Tecmo", 'NA'],
			["Ninja Gaiden III: The Ancient Ship of Doom", 1991, "Tecmo", 'NA'],
			["Ninja Kid", 1986, "Bandai", 'NA'],
			["Nintendo World Cup", 1990, "Nintendo", 'NA'],
			["Nobunaga's Ambition", 1989, "Koei", 'NA'],
			["Nobunaga's Ambition II", 1991, "Koei", 'NA'],
			["North & South", 1990, "Kemco", 'NA'],
			["Operation Wolf", 1989, "Taito", 'NA'],
			["Orb 3-D", 1990, "Hi-Tech Expressions", 'NA'],
			["Othello", 1988, "Acclaim", 'NA'],
			["Overlord", 1993, "Virgin Games", 'NA'],
			["P.O.W.: Prisoners of War", 1989, "SNK", 'NA'],
			["Pac-Man (Namco)", 1993, "Namco", 'NA'],
			["Pac-Man (Tengen -- licensed grey cart)", 1987, "Tengen", 'NA'],
			["Palamedes", 1990, "Hot-B", 'NA'],
			["Panic Restaurant", 1992, "Taito", 'NA'],
			["Paperboy", 1988, "Mindscape", 'NA'],
			["Paperboy 2", 1992, "Mindscape", 'NA'],
			["Peter Pan & the Pirates", 1991, "THQ", 'NA'],
			["Phantom Fighter", 1990, "FCI", 'NA'],
			["Pictionary", 1990, "LJN", 'NA'],
			["Pin*Bot", 1990, "Nintendo", 'NA'],
			["Pinball", 1985, "Nintendo", 'NA'],
			["Pinball Quest", 1990, "Jaleco", 'NA'],
			["Pipe Dream", 1990, "Bullet Proof Software", 'NA'],
			["Pirates!", 1991, "Ultra Games (Konami)", 'NA'],
			["Platoon", 1988, "Sunsoft", 'NA'],
			["Popeye", 1986, "Nintendo", 'NA'],
			["Power Blade", 1991, "Taito", 'NA'],
			["Power Blade 2", 1992, "Taito", 'NA'],
			["Power Punch II", 1992, "American Softworks", 'NA'],
			["Predator", 1989, "Activision", 'NA'],
			["Prince of Persia", 1992, "Virgin Games", 'NA'],
			["Princess Tomato in the Salad Kingdom", 1991, "Hudson Soft", 'NA'],
			["Pro Sport Hockey", 1993, "Jaleco", 'NA'],
			["Pro Wrestling", 1987, "Nintendo", 'NA'],
			["Punch-Out!!", 1990, "Nintendo", 'NA'],
			["Punisher, The", 1990, "LJN", 'NA'],
			["Puss 'N Boots: Pero's Great Adventure", 1990, "Electro Brain", 'NA'],
			["Puzznic", 1990, "Taito", 'NA'],
			["Q*bert", 1989, "Ultra Games (Konami)", 'NA'],
			["Qix", 1991, "Taito", 'NA'],
			["R.B.I. Baseball (licensed grey cart)", 1988, "Tengen", 'NA'],
			["R.C. Pro-Am", 1988, "Nintendo", 'NA'],
			["R.C. Pro-Am II", 1992, "Tradewest", 'NA'],
			["Race America", 1992, "Absolute", 'NA'],
			["Racket Attack", 1988, "Jaleco", 'NA'],
			["Rad Racer", 1987, "Nintendo", 'NA'],
			["Rad Racer II", 1990, "Square", 'NA'],
			["Raid on Bungeling Bay", 1987, "Broderbund", 'NA'],
			["Rainbow Islands", 1991, "Taito", 'NA'],
			["Rally Bike", 1990, "Romstar", 'NA'],
			["Rambo", 1988, "Acclaim", 'NA'],
			["Rampage", 1988, "Data East", 'NA'],
			["Rampart", 1992, "Jaleco", 'NA'],
			["Remote Control", 1990, "Hi-Tech Expressions", 'NA'],
			["Ren & Stimpy Show, The: Buckeroo$!", 1993, "THQ", 'NA'],
			["Renegade", 1988, "Taito", 'NA'],
			["Rescue: The Embassy Mission", 1990, "Kemco", 'NA'],
			["Ring King", 1987, "Data East", 'NA'],
			["River City Ransom", 1990, "American Technos", 'NA'],
			["RoadBlasters", 1990, "Mindscape", 'NA'],
			["Robin Hood: Prince of Thieves", 1991, "Virgin Games", 'NA'],
			["Robo Warrior", 1988, "Jaleco", 'NA'],
			["RoboCop", 1989, "Data East", 'NA'],
			["RoboCop 2", 1991, "Data East", 'NA'],
			["RoboCop 3", 1992, "Ocean Software", 'NA'],
			["Rock 'n Ball", 1990, "NTVIC", 'NA'],
			["Rocket Ranger", 1990, "Kemco", 'NA'],
			["Rocketeer, The", 1991, "Bandai", 'NA'],
			["Rockin' Kats", 1991, "Atlus", 'NA'],
			["Roger Clemens' MVP Baseball", 1991, "LJN", 'NA'],
			["Rollerball", 1990, "HAL Laboratory", 'NA'],
			["Rollerblade Racer", 1993, "Hi-Tech Expressions", 'NA'],
			["Rollergames", 1990, "Ultra Games (Konami)", 'NA'],
			["Romance of the Three Kingdoms", 1989, "Koei", 'NA'],
			["Romance of the Three Kingdoms II", 1991, "Koei", 'NA'],
			["Roundball: 2-on-2 Challenge", 1992, "Mindscape", 'NA'],
			["Rush'n Attack", 1987, "Konami", 'NA'],
			["Rygar", 1987, "Tecmo", 'NA'],
			["S.C.A.T.: Special Cybernetic Attack Team", 1991, "Natsume", 'NA'],
			["Section-Z", 1987, "Capcom", 'NA'],
			["Seicross", 1988, "FCI", 'NA'],
			["Sesame Street 123", 1989, "Hi-Tech Expressions", 'NA'],
			["Sesame Street ABC", 1989, "Hi-Tech Expressions", 'NA'],
			["Sesame Street ABC/123", 1991, "Hi-Tech Expressions", 'NA'],
			["Sesame Street Countdown", 1992, "Hi-Tech Expressions", 'NA'],
			["Sesame Street: Big Bird's Hide & Speak", 1990, "Hi-Tech Expressions", 'NA'],
			["Shadow of the Ninja", 1990, "Natsume", 'NA'],
			["Shadowgate", 1989, "Kemco", 'NA'],
			["Shatterhand", 1991, "Jaleco", 'NA'],
			["Shingen the Ruler", 1990, "Hot-B", 'NA'],
			["Shooting Range", 1989, "Bandai", 'NA'],
			["Short Order/Eggsplode!", 1989, "Nintendo", 'NA'],
			["Side Pocket", 1987, "Data East", 'NA'],
			["Silent Service", 1989, "Ultra Games (Konami)", 'NA'],
			["Silkworm", 1990, "American Sammy", 'NA'],
			["Silver Surfer", 1990, "Arcadia Systems", 'NA'],
			["Simpsons, The: Bart vs. the Space Mutants", 1991, "Acclaim", 'NA'],
			["Simpsons, The: Bart vs. the World", 1991, "Acclaim", 'NA'],
			["Simpsons, The: Bartman Meets Radioactive Man", 1992, "Acclaim", 'NA'],
			["Skate or Die", 1988, "Ultra Games (Konami)", 'NA'],
			["Skate or Die 2: The Search for Double Trouble", 1990, "Electronic Arts", 'NA'],
			["Ski or Die", 1991, "Ultra Games (Konami)", 'NA'],
			["Sky Kid", 1987, "Sunsoft", 'NA'],
			["Sky Shark", 1989, "Taito", 'NA'],
			["Slalom", 1987, "Nintendo", 'NA'],
			["Smash T.V.", 1991, "Acclaim", 'NA'],
			["Snake Rattle 'n' Roll", 1990, "Nintendo", 'NA'],
			["Snake's Revenge", 1990, "Ultra Games (Konami)", 'NA'],
			["Snoopy's Silly Sports Spectacular!", 1990, "Kemco", 'NA'],
			["Snow Brothers", 1991, "Capcom", 'NA'],
			["Soccer", 1987, "Nintendo", 'NA'],
			["Solar Jetman: Hunt for the Golden Warpship", 1990, "Tradewest", 'NA'],
			["Solomon's Key", 1987, "Tecmo", 'NA'],
			["Solstice: The Quest for the Staff of Demnos", 1990, "Sony Imagesoft", 'NA'],
			["Space Shuttle Project", 1991, "Absolute", 'NA'],
			["Spelunker", 1987, "Broderbund", 'NA'],
			["Spider-Man: Return of the Sinister Six", 1992, "LJN", 'NA'],
			["Spot: The Video Game", 1990, "Arcadia Systems", 'NA'],
			["Spy Hunter", 1987, "Sunsoft", 'NA'],
			["Spy vs. Spy", 1988, "Kemco", 'NA'],
			["Sqoon", 1987, "Irem", 'NA'],
			["Stack-Up", 1985, "Nintendo", 'NA'],
			["Stadium Events", 1987, "Bandai", 'NA'],
			["Stanley: The Search for Dr. Livingston", 1992, "Electro Brain", 'NA'],
			["Star Force", 1987, "Tecmo", 'NA'],
			["Star Soldier", 1989, "Taxan", 'NA'],
			["Star Trek: 25th Anniversary", 1992, "Ultra Games (Konami)", 'NA'],
			["Star Trek: The Next Generation", 1993, "Absolute", 'NA'],
			["Star Voyager", 1987, "Acclaim", 'NA'],
			["Star Wars", 1991, "JVC", 'NA'],
			["Star Wars: The Empire Strikes Back", 1992, "JVC", 'NA'],
			["Starship Hector", 1990, "Hudson Soft", 'NA'],
			["StarTropics", 1990, "Nintendo", 'NA'],
			["Stealth ATF", 1989, "Activision", 'NA'],
			["Stinger", 1987, "Konami", 'NA'],
			["Street Cop", 1989, "Bandai", 'NA'],
			["Street Fighter 2010: The Final Fight", 1990, "Capcom", 'NA'],
			["Strider", 1989, "Capcom", 'NA'],
			["Super C", 1990, "Konami", 'NA'],
			["Super Cars", 1991, "Electro Brain", 'NA'],
			["Super Dodge Ball", 1989, "Sony Imagesoft", 'NA'],
			["Super Glove Ball", 1990, "Mattel Electronics", 'NA'],
			["Super Jeopardy!", 1991, "GameTek", 'NA'],
			["Super Mario Bros.", 1985, "Nintendo", 'NA'],
			["Super Mario Bros. 2", 1988, "Nintendo", 'NA'],
			["Super Mario Bros. 3", 1990, "Nintendo", 'NA'],
			["Super Mario Bros./Duck Hunt", 1988, "Nintendo", 'NA'],
			["Super Mario Bros./Duck Hunt/World Class Track Meet", 1990, "Nintendo", 'NA'],
			["Super Pitfall", 1987, "Activision", 'NA'],
			["Super Spike V'Ball", 1990, "Nintendo", 'NA'],
			["Super Spike V'Ball/Nintendo World Cup", 1990, "Nintendo", 'NA'],
			["Super Spy Hunter", 1992, "Sunsoft", 'NA'],
			["Super Team Games", 1988, "Nintendo", 'NA'],
			["Superman", 1988, "Kemco", 'NA'],
			["Swamp Thing", 1992, "THQ", 'NA'],
			["Sword Master", 1992, "Activision", 'NA'],
			["Swords and Serpents", 1990, "Acclaim", 'NA'],
			["Taboo: The Sixth Sense", 1989, "Tradewest", 'NA'],
			["Tag Team Wrestling", 1986, "Data East", 'NA'],
			["TaleSpin", 1991, "Capcom", 'NA'],
			["Target: Renegade", 1990, "Taito", 'NA'],
			["Tecmo Baseball", 1989, "Tecmo", 'NA'],
			["Tecmo Bowl", 1989, "Tecmo", 'NA'],
			["Tecmo Cup Soccer Game", 1992, "Tecmo", 'NA'],
			["Tecmo NBA Basketball", 1992, "Tecmo", 'NA'],
			["Tecmo Super Bowl", 1991, "Tecmo", 'NA'],
			["Tecmo World Wrestling", 1990, "Tecmo", 'NA'],
			["Teenage Mutant Ninja Turtles", 1989, "Ultra Games (Konami)", 'NA'],
			["Teenage Mutant Ninja Turtles II: The Arcade Game", 1990, "Ultra Games (Konami)", 'NA'],
			["Teenage Mutant Ninja Turtles III: The Manhattan Project", 1992, "Konami", 'NA'],
			["Teenage Mutant Ninja Turtles: Tournament Fighters", 1994, "Konami", 'NA'],
			["Tennis", 1985, "Nintendo", 'NA'],
			["Terminator 2: Judgment Day", 1992, "LJN", 'NA'],
			["Terminator, The", 1992, "Mindscape", 'NA'],
			["Terra Cresta", 1990, "Vic Tokai", 'NA'],
			["Tetris (Nintendo)", 1989, "Nintendo", 'NA'],
			["Tetris 2", 1993, "Nintendo", 'NA'],
			["Three Stooges, The", 1989, "Activision", 'NA'],
			["Thunder & Lightning", 1990, "Romstar", 'NA'],
			["Thunderbirds", 1990, "Activision", 'NA'],
			["Thundercade", 1989, "American Sammy", 'NA'],
			["Tiger-Heli", 1987, "Acclaim", 'NA'],
			["Time Lord", 1990, "Milton Bradley", 'NA'],
			["Times of Lore", 1991, "Toho", 'NA'],
			["Tiny Toon Adventures", 1991, "Konami", 'NA'],
			["Tiny Toon Adventures 2: Trouble in Wackyland", 1993, "Konami", 'NA'],
			["Tiny Toon Adventures Cartoon Workshop", 1992, "Konami", 'NA'],
			["To the Earth", 1989, "Nintendo", 'NA'],
			["Toki", 1991, "Taito", 'NA'],
			["Tom & Jerry: The Ultimate Game of Cat and Mouse!", 1991, "Hi-Tech Expressions", 'NA'],
			["Tombs & Treasure", 1991, "Infocom", 'NA'],
			["Top Gun", 1987, "Konami", 'NA'],
			["Top Gun: The Second Mission", 1990, "Konami", 'NA'],
			["Top Players' Tennis Featuring Chris Evert & Ivan Lendl", 1990, "Asmik", 'NA'],
			["Total Recall", 1990, "Acclaim", 'NA'],
			["Totally Rad", 1991, "Jaleco", 'NA'],
			["Touchdown Fever", 1991, "SNK", 'NA'],
			["Town & Country II: Thrilla's Surfari", 1992, "LJN", 'NA'],
			["Town & Country Surf Designs: Wood & Water Rage", 1988, "LJN", 'NA'],
			["Toxic Crusaders", 1992, "Bandai", 'NA'],
			["Track & Field", 1987, "Konami", 'NA'],
			["Track & Field II", 1989, "Konami", 'NA'],
			["Treasure Master", 1991, "American Softworks", 'NA'],
			["Trog!", 1991, "Acclaim", 'NA'],
			["Trojan", 1987, "Capcom", 'NA'],
			["Twin Cobra", 1990, "American Sammy", 'NA'],
			["Twin Eagle", 1989, "Romstar", 'NA'],
			["Ultima: Exodus", 1989, "FCI", 'NA'],
			["Ultima: Quest of the Avatar", 1990, "FCI", 'NA'],
			["Ultima: Warriors of Destiny", 1993, "FCI", 'NA'],
			["Ultimate Air Combat", 1992, "Activision", 'NA'],
			["Ultimate Basketball", 1990, "American Sammy", 'NA'],
			["Uncanny X-Men, The", 1989, "LJN", 'NA'],
			["Uncharted Waters", 1991, "Koei", 'NA'],
			["Uninvited", 1991, "Kemco", 'NA'],
			["Untouchables, The (black label)", 1991, "Ocean Software", 'NA'],
			["Untouchables, The (blue label)", 1991, "Ocean Software", 'NA'],
			["Urban Champion", 1986, "Nintendo", 'NA'],
			["Vegas Dream", 1990, "HAL Laboratory", 'NA'],
			["Vice: Project Doom", 1991, "American Sammy", 'NA'],
			["Videomation", 1991, "THQ", 'NA'],
			["Volleyball", 1987, "Nintendo", 'NA'],
			["Wacky Races", 1992, "Atlus", 'NA'],
			["Wall Street Kid", 1990, "Sofel", 'NA'],
			["Wario's Woods", 1994, "Nintendo", 'NA'],
			["Wayne Gretzky Hockey (black uniform)", 1991, "THQ", 'NA'],
			["Wayne Gretzky Hockey (white uniform)", 1991, "THQ", 'NA'],
			["Wayne's World", 1993, "THQ", 'NA'],
			["WCW World Championship Wrestling", 1990, "FCI", 'NA'],
			["Werewolf: The Last Warrior", 1990, "Data East", 'NA'],
			["Wheel of Fortune", 1988, "GameTek", 'NA'],
			["Wheel of Fortune: Family Edition", 1990, "GameTek", 'NA'],
			["Wheel of Fortune: Featuring Vanna White", 1992, "GameTek", 'NA'],
			["Wheel of Fortune: Junior Edition", 1989, "GameTek", 'NA'],
			["Where in Time Is Carmen Sandiego?", 1991, "Konami", 'NA'],
			["Where's Waldo?", 1991, "THQ", 'NA'],
			["Who Framed Roger Rabbit", 1989, "LJN", 'NA'],
			["Whomp 'Em", 1991, "Jaleco", 'NA'],
			["Widget", 1992, "Atlus", 'NA'],
			["Wild Gunman", 1985, "Nintendo", 'NA'],
			["Willow", 1989, "Capcom", 'NA'],
			["Win, Lose or Draw", 1990, "Hi-Tech Expressions", 'NA'],
			["Winter Games", 1987, "Acclaim", 'NA'],
			["Wizardry: Knight of Diamonds - The Second Scenario", 1992, "ASCII", 'NA'],
			["Wizardry: Proving Grounds of the Mad Overlord", 1990, "Nexoft", 'NA'],
			["Wizards & Warriors", 1987, "Acclaim", 'NA'],
			["Wizards & Warriors III: Kuros - Visions of Power", 1992, "Acclaim", 'NA'],
			["Wolverine", 1991, "LJN", 'NA'],
			["World Champ", 1991, "Romstar", 'NA'],
			["World Class Track Meet", 1988, "Nintendo", 'NA'],
			["World Games", 1989, "Milton Bradley", 'NA'],
			["Wrath of the Black Manta", 1990, "Taito", 'NA'],
			["Wrecking Crew", 1985, "Nintendo", 'NA'],
			["WURM: Journey to the Center of the Earth", 1991, "Asmik", 'NA'],
			["WWF King of the Ring", 1993, "Acclaim", 'NA'],
			["WWF WrestleMania", 1989, "Acclaim", 'NA'],
			["WWF WrestleMania Challenge", 1990, "LJN", 'NA'],
			["WWF WrestleMania: Steel Cage Challenge", 1992, "LJN", 'NA'],
			["Xenophobe", 1988, "Sunsoft", 'NA'],
			["Xevious", 1988, "Bandai", 'NA'],
			["Xexyz", 1990, "Hudson Soft", 'NA'],
			["Yo! Noid", 1990, "Capcom", 'NA'],
			["Yoshi", 1992, "Nintendo", 'NA'],
			["Yoshi's Cookie", 1993, "Nintendo", 'NA'],
			["Young Indiana Jones Chronicles, The", 1992, "Jaleco", 'NA'],
			["Zanac", 1987, "FCI", 'NA'],
			["Zelda II: The Adventure of Link (original -- gold cartridge)", 1988, "Nintendo", 'NA'],
			["Zelda II: The Adventure of Link (reissue -- grey cartridge)", 1992, "Nintendo", 'NA'],
			["Zen: Intergalactic Ninja", 1993, "Konami", 'NA'],
			["Zoda's Revenge: StarTropics II", 1994, "Nintendo", 'NA'],
			["Zombie Nation", 1991, "Meldac", 'NA'],
		];

		foreach ($games as $game) {
			DB::table('games')->insert([
				'platform' => 'NES',
				'name' => $game[0],
				'release_date' => $game[1],
				'publisher' => $game[2],
				'region' => $game[3],
				'created_at' => \Carbon\Carbon::now(),
				'updated_at' => \Carbon\Carbon::now(),
			]);
		}
	}
}
