<?php

use Illuminate\Database\Seeder;

class SNESSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $games = [
	        ["3 Ninjas Kick Back","June 19, 1994","Malibu Interactive","Sony Imagesoft","Platformer", 'NA'],
	        ["The 7th Saga","August 3, 1993","Produce","Enix","Role-playing", 'NA'],
	        ["A.S.P. Air Strike Patrol","January 1, 1995","SETA","SETA","Isometric Shoot 'em Up", 'NA'],
	        ["AAAHH!!! Real Monsters","August 15, 1995","Realtime Associates","Viacom New Media","Platformer", 'NA'],
	        ["ABC Monday Night Football","December 7, 1993","Data East / Kuusoukagaku","Data East","Football", 'NA'],
	        ["Acme Animation Factory","November 5, 1994","Sunsoft","Sunsoft","Educational Animator", 'NA'],
	        ["ActRaiser","November 1, 1991","Quintet","Enix","Simulation/Platformer", 'NA'],
	        ["ActRaiser 2","November 16, 1993","Quintet","Enix","Platformer", 'NA'],
	        ["The Addams Family","March 10, 1992","Ocean Software","Ocean Software","Platformer", 'NA'],
	        ["The Addams Family: Pugsley's Scavenger Hunt","February 23, 1993","Ocean Software","Ocean Software","Platformer", 'NA'],
	        ["Addams Family Values","February 14, 1995","Ocean Software","Ocean Software","Action Role-playing", 'NA'],
	        ["The Adventures of Batman & Robin","December 1, 1994","Konami","Konami","Action Platformer", 'NA'],
	        ["The Adventures of Dr. Franken","December 1, 1993","MotiveTime","DTMC","Platformer", 'NA'],
	        ["The Adventures of Kid Kleets","December 1, 1993","Krisalis Software","Ocean Software","Platformer", 'NA'],
	        ["The Adventures of Mighty Max","February 7, 1995","Ocean Software","Ocean Software","Platformer", 'NA'],
	        ["The Adventures of Rocky and Bullwinkle and Friends","June 1, 1993","Imagineering","THQ","Platformer", 'NA'],
	        ["Adventures of Yogi Bear","October 1, 1994","Empire Software","Cybersoft","Platformer", 'NA'],
	        ["Aero Fighters","November 1, 1994","Video System","Video System","Scrolling Shooter", 'NA'],
	        ["Aero the Acro-Bat","October 12, 1993","Iguana Entertainment","Sunsoft","Platformer", 'NA'],
	        ["Aero the Acro-Bat 2","November 1, 1994","Iguana Entertainment","Sunsoft","Platformer", 'NA'],
	        ["Aerobiz","February 2, 1993","Koei","Koei","Simulation", 'NA'],
	        ["Aerobiz Supersonic","August 29, 1994","Koei","Koei","Simulation", 'NA'],
	        ["Air Cavalry","June 20, 1995","Synergistic Software","Cybersoft","Flight Simulation/Shoot 'em Up", 'NA'],
	        ["Al Unser Jr.'s Road to the Top","November 1, 1994","Radical Entertainment","Mindscape","Racing", 'NA'],
	        ["Alfred Chicken","February 1, 1994","Twilight Games","Mindscape","Platformer", 'NA'],
	        ["Alien 3","May 17, 1993","Probe Entertainment","Acclaim Entertainment","Platformer", 'NA'],
	        ["Alien vs Predator","September 4, 1993","Jorudan","Activision","Beat 'Em Up", 'NA'],
	        ["American Gladiators","April 13, 1993","Imagitec Design","GameTek","Sports", 'NA'],
	        ["An American Tail: Fievel Goes West","August 30, 1994","Hudson Soft","Hudson Soft","Platformer", 'NA'],
	        ["Andre Agassi Tennis","May 31, 1994","Radiance Software","TecMagik","Tennis", 'NA'],
	        ["Animaniacs","November 1, 1994","Konami","Konami","Platformer", 'NA'],
	        ["Arcade's Greatest Hits: The Atari Collection 1","August 30, 1997","Digital Eclipse Software","Midway Games","Arcade Compilation", 'NA'],
	        ["Arcana","May 5, 1992","HAL Laboratory","HAL Laboratory","Role-playing", 'NA'],
	        ["Ardy Lightfoot","June 1, 1993","ASCII Entertainment","Titus Software","Platformer", 'NA'],
	        ["Arkanoid: Doh It Again","October 1, 1997","Taito","Nintendo","Breakout", 'NA'],
	        ["Art of Fighting","December 1, 1993","Monolith Corporation","Takara","Fighting", 'NA'],
	        ["Axelay","September 14, 1992","Konami","Konami","Scrolling Shooter", 'NA'],
	        ["B.O.B.","June 1, 1993","Gray Matter","Electronic Arts","Run and Gun", 'NA'],
	        ["Ballz 3D","April 1, 1994","PF Magic","Accolade","Fighting", 'NA'],
	        ["Barbie Super Model","June 16, 1993","Software Creations","Hi Tech Expressions","Educational Action", 'NA'],
	        ["Barkley Shut Up and Jam!","June 7, 1994","Accolade","Accolade","Basketball", 'NA'],
	        ["Bass Masters Classic","June 6, 1995","Malibu Games","Malibu Games","Fishing", 'NA'],
	        ["Bass Masters Classic: Pro Edition","July 23, 1996","Black Pearl Software","Black Pearl Software","Fishing", 'NA'],
	        ["Bassin's Black Bass with Hank Parker","November 1, 1994","Starfish","Hot-B","Fishing", 'NA'],
	        ["Batman Forever","October 26, 1995","Probe Entertainment","Acclaim Entertainment","Beat 'Em Up", 'NA'],
	        ["Batman Returns","May 31, 1993","Konami","Konami","Beat 'Em Up", 'NA'],
	        ["Battle Blaze","October 19, 1993","Aicom","American Sammy","Fighting", 'NA'],
	        ["Battle Cars","October 11, 1993","Namco","Namco","Vehicular combat", 'NA'],
	        ["Battle Clash","October 1, 1992","Intelligent Systems","Nintendo","Light Gun Shooter", 'NA'],
	        ["Battle Grand Prix","April 20, 1993","KID","Hudson Soft","Racing/Vehicular Combat", 'NA'],
	        ["Battletoads & Double Dragon","December 1, 1993","Rare","Tradewest","Beat 'Em Up", 'NA'],
	        ["Battletoads in Battlemaniacs","June 29, 1993","Rare","Tradewest","Beat 'Em Up/Platformer", 'NA'],
	        ["Bazooka Blitzkrieg","December 31, 1992","Tose","Bandai","Rail Shooter", 'NA'],
	        ["Beavis and Butt-head","November 1, 1994","Realtime Associates","Viacom New Media","Action", 'NA'],
	        ["Bébé's Kids","April 19, 1994","Radical Entertainment","Motown Software","Beat 'em Up", 'NA'],
	        ["Beethoven: The Ultimate Canine Caper","December 17, 1993","Riedel Software Productions","Hi Tech Expressions","Platformer", 'NA'],
	        ["Best of the Best: Championship Karate","November 24, 1993","Loriciel","Electro Brain","Fighting", 'NA'],
	        ["Big Sky Trooper","October 10, 1995","LucasArts","JVC","Action Role-playing", 'NA'],
	        ["Biker Mice from Mars","December 1, 1994","Konami","Konami","Racing", 'NA'],
	        ["Bill Laimbeer's Combat Basketball","December 1, 1991","Hudson Soft","Hudson Soft","Basketball", 'NA'],
	        ["Bill Walsh College Football","June 1, 1993","EA Sports","Visual Concepts","Football", 'NA'],
	        ["BioMetal","June 1, 1993","Athena","Activision","Scrolling shooter", 'NA'],
	        ["Blackthorne","August 10, 1995","Blizzard Entertainment","Interplay Entertainment","Cinematic Platformer", 'NA'],
	        ["BlaZeon: The Bio-Cyborg Challenge","October 27, 1992","AI","Atlus","Scrolling shooter", 'NA'],
	        ["The Blues Brothers","June 1, 1993","Titus Software","Titus Software","Platformer", 'NA'],
	        ["Boogerman: A Pick and Flick Adventure","September 15, 1995","Interplay Entertainment","Interplay Entertainment","Platformer", 'NA'],
	        ["Boxing Legends of the Ring","November 1, 1994","Sculptured Software","Electro Brain","Boxing, Fighting", 'NA'],
	        ["Brain Lord","October 1, 1994","Produce","Enix","Action Role-playing", 'NA'],
	        ["The Brainies","April 2, 1996","Titus Software","Titus Software","Puzzle", 'NA'],
	        ["Bram Stoker's Dracula","January 1, 1993","Psygnosis","Sony Imagesoft","Platformer", 'NA'],
	        ["Brandish","February 28. 1995","Koei","Koei","Dungeon Crawler/Action Role-playing", 'NA'],
	        ["Brawl Brothers","April 13, 1993","Jaleco","Jaleco","Beat 'Em Up", 'NA'],
	        ["BreakThru!","June 1, 1994","Artech Digital Entertainment","Spectrum Holobyte","Puzzle", 'NA'],
	        ["Breath of Fire","August 10, 1994","Capcom","Square","Role-playing", 'NA'],
	        ["Breath of Fire II","December 10, 1995","Capcom","Capcom","Role-playing", 'NA'],
	        ["Brett Hull Hockey","January 11, 1994","Radical Entertainment","Accolade","Hockey", 'NA'],
	        ["Brett Hull Hockey '95","September 9, 1994","Radical Entertainment","Accolade","Hockey", 'NA'],
	        ["Bronkie the Bronchiasaurus","September 26, 1995","WaveQuest","Raya Systems","Educational Platformer", 'NA'],
	        ["Brunswick World: Tournament of Champions","August 12, 1997","Tiertex Design Studios","THQ","Bowling", 'NA'],
	        ["Brutal: Paws of Fury","December 6, 1994","Eurocom","GameTek","Fighting", 'NA'],
	        ["Bubsy in Claws Encounters of the Furred Kind","May 1, 1993","Accolade","Accolade","Platformer", 'NA'],
	        ["Bubsy 2","April 3, 1994","Accolade","Accolade","Platformer", 'NA'],
	        ["Bugs Bunny Rabbit Rampage","February 15, 1994","Sunsoft","Sunsoft","Platformer", 'NA'],
	        ["Bulls versus Blazers and the NBA Playoffs","December 1, 1992","Electronic Arts","EA Sports","Basketball", 'NA'],
	        ["Bust-a-Move","March 1, 1995","Taito","Taito","Puzzle", 'NA'],
	        ["Cacoma Knight in Bizyland","June 1, 1993","SETA","SETA","Action/Puzzle", 'NA'],
	        ["Cal Ripken Jr. Baseball","December 1, 1992","Mindscape","Mindscape","Baseball", 'NA'],
	        ["California Games 2","January 1, 1993","Silicon Sorcery","DTMC","Sports", 'NA'],
	        ["Capcom's MVP Football","June 1, 1992","Equilibrium","Capcom","Football", 'NA'],
	        ["Capcom's Soccer Shootout","September 15, 1994","Capcom","Capcom","Soccer", 'NA'],
	        ["Captain America and The Avengers","September 1, 1993","Mindscape","Mindscape","Beat 'Em Up", 'NA'],
	        ["Captain Commando","August 1, 1995","Capcom","Capcom","Beat 'Em Up", 'NA'],
	        ["Captain Novolin","November 2, 1992","Sculptured Software","Raya Systems","Educational Platformer", 'NA'],
	        ["Carrier Aces","January 1, 1995","Synergistic Software","Cybersoft","War/Action Simulator", 'NA'],
	        ["Casper","December 1, 1996","Absolute Entertainment","Natsume","Action", 'NA'],
	        ["Castlevania: Dracula X","September 1, 1995","Konami","Konami","Platformer", 'NA'],
	        ["Champions World Class Soccer","November 4, 1994","Park Place Productions","Acclaim Entertainment","Soccer", 'NA'],
	        ["Championship Pool","November 3, 1993","Bitmasters","Mindscape","Billiards", 'NA'],
	        ["Championship Soccer '94","June 23, 1994","Sensible Software","Sony Imagesoft","Soccer", 'NA'],
	        ["The Chessmaster","September 1, 1991","Mindscape","Mindscape","Board Game", 'NA'],
	        ["Chester Cheetah: Too Cool to Fool","December 2, 1992","Kaneko","Kaneko","Platformer", 'NA'],
	        ["Chester Cheetah: Wild Wild Quest","March 1, 1994","Kaneko","Kaneko","Platformer", 'NA'],
	        ["Choplifter III","January 1, 1994","Beam Software","Extreme Entertainment Group","Shoot 'em Up", 'NA'],
	        ["Chrono Trigger","August 22, 1995","Square","Square","Role-playing", 'NA'],
	        ["Chuck Rock","November 1, 1992","Core Design","Sony Imagesoft","Platformer", 'NA'],
	        ["Civilization","June 30, 1995","Microprose","Koei","Turn-based Strategy", 'NA'],
	        ["ClayFighter","November 30, 1993","Visual Concepts","Interplay Entertainment","Fighting", 'NA'],
	        ["ClayFighter: Tournament Edition","November 22, 1994","Visual Concepts","Interplay Entertainment","Fighting", 'NA'],
	        ["ClayFighter 2: Judgment Clay","January 1, 1995","Interplay Entertainment","Interplay Entertainment","Fighting", 'NA'],
	        ["Claymates","April 26, 1993","Visual Concepts","Interplay Entertainment","Platformer", 'NA'],
	        ["Cliffhanger","October 25, 1993","Malibu Interactive","Sony Imagesoft","Beat 'Em Up", 'NA'],
	        ["Clue","July 1, 1992","Sculptured Software","Parker Brothers","Board game", 'NA'],
	        ["College Football USA '97: The Road to New Orleans","June 1, 1996","Black Pearl Software","EA Sports","Football", 'NA'],
	        ["College Slam","January 31, 1996","Iguana Entertainment","Acclaim Entertainment","Basketball", 'NA'],
	        ["The Combatribes","March 1, 1993","Technōs Japan","American Technōs","Beat 'Em Up", 'NA'],
	        ["Congo's Caper","May 1, 1993","Data East","Data East","Platformer", 'NA'],
	        ["Contra III: The Alien Wars","April 6, 1992","Konami","Konami","Platformer/Run and Gun", 'NA'],
	        ["Cool Spot","September 1, 1993","Virgin Interactive","Virgin Interactive","Platformer", 'NA'],
	        ["Cool World","February 1, 1993","Ocean Software","Ocean Software","Action", 'NA'],
	        ["Cutthroat Island","March 1, 1996","Software Creations (UK)","Acclaim Entertainment","Beat 'Em Up", 'NA'],
	        ["Cyber Spin","November 1, 1992","Takara","Takara","Racing", 'NA'],
	        ["Cybernator","April 4, 1993","NCS","Konami","Platformer/Run and Gun", 'NA'],
	        ["Daffy Duck: The Marvin Missions","October 1, 1993","ICOM Simulations","Sunsoft","Platformer", 'NA'],
	        ["Darius Twin","November 30, 1991","Taito","Taito","Scrolling Shooter", 'NA'],
	        ["David Crane's Amazing Tennis","November 5, 1992","David Crane","Absolute Entertainment","Tennis", 'NA'],
	        ["The Death and Return of Superman","August 1, 1994","Blizzard Entertainment","Sunsoft","Beat 'Em Up", 'NA'],
	        ["Demolition Man","August 1, 1995","Virgin Interactive","Acclaim Entertainment","Action/Platformer", 'NA'],
	        ["Demon's Crest","November 1, 1994","Capcom","Capcom","Action/Platformer", 'NA'],
	        ["Dennis the Menace","December 1, 1993","Ocean Software","Ocean Software","Platformer", 'NA'],
	        ["Desert Strike: Return to the Gulf","October 1, 1992","Visual Concepts","Electronic Arts","Shoot 'Em Up", 'NA'],
	        ["D-Force","December 31, 1991","Asmik Ace Entertainment","Asmik Ace Entertainment","Scrolling Shooter", 'NA'],
	        ["Dig & Spike Volleyball","December 1, 1993","Tose","Hudson Soft","Volleyball", 'NA'],
	        ["DinoCity","September 4, 1992","Irem","Irem","Platformer", 'NA'],
	        ["Dirt Trax FX","June 16, 1995","Sculptured Software","Acclaim Entertainment","Racing", 'NA'],
	        ["Disney's Aladdin","November 21, 1993","Capcom","Capcom","Platformer", 'NA'],
	        ["Disney's Beauty and the Beast","July 1994","Probe Software","Hudson Soft","Platformer", 'NA'],
	        ["Disney's Bonkers","December 15, 1994","Sun L","Capcom","Platformer", 'NA'],
	        ["Disney's Pinocchio","November 1, 1996","Virgin Interactive","Disney Interactive","Platformer", 'NA'],
	        ["Donkey Kong Country","November 21, 1994","Rare","Nintendo","Platformer", 'NA'],
	        ["Donkey Kong Country 2: Diddy's Kong Quest","November 20, 1995","Rare","Nintendo","Platformer", 'NA'],
	        ["Donkey Kong Country 3: Dixie Kong's Double Trouble!","November 22, 1996","Rare","Nintendo","Platformer", 'NA'],
	        ["Doom","September 1, 1995","Sculptured Software","Williams Entertainment","First-Person Shooter", 'NA'],
	        ["Doom Troopers","November 15, 1995","Adrenalin Interactive","Playmates","Run and Gun", 'NA'],
	        ["Doomsday Warrior","April 30, 1993","Telenet","Renovation Products","Fighting", 'NA'],
	        ["Double Dragon V: The Shadow Falls","August 5, 1994","Leland Interactive Media","Tradewest","Fighting", 'NA'],
	        ["Dragon: The Bruce Lee Story","July 1, 1995","Virgin Interactive","Acclaim Entertainment","Fighting", 'NA'],
	        ["Dragon View","November 17, 1994","Infogrames","Kemco","Action Role-playing", 'NA'],
	        ["Dragon's Lair","February 1, 1993","MotiveTime","Data East","Action/Platformer", 'NA'],
	        ["Drakkhen","September 1, 1991","Infogrames","Kemco","Role-playing", 'NA'],
	        ["Dream TV","April 1, 1994","Triffix","Triffix","Action", 'NA'],
	        ["The Duel: Test Drive II","December 1, 1992","Distinctive Software","Accolade","Racing", 'NA'],
	        ["Dungeon Master","June 1, 1993","Software Heaven / FTL Games","JVC","Role-playing", 'NA'],
	        ["E.V.O.: Search for Eden","July 15, 1993","Almanic","Enix","Action Role-playing", 'NA'],
	        ["Earth Defense Force","January 1, 1992","Jaleco","Jaleco","Scrolling Shooter", 'NA'],
	        ["EarthBound","June 5, 1995","HAL Laboratory/Ape, Inc.","Nintendo","Role-playing", 'NA'],
	        ["Earthworm Jim","October 2, 1994","Shiny Entertainment","Playmates","Platformer", 'NA'],
	        ["Earthworm Jim 2","January 1, 1996","Shiny Entertainment","Playmates","Platformer", 'NA'],
	        ["Eek! The Cat","August 1, 1994","CTA Developments","Ocean Software","Platformer/Strategy", 'NA'],
	        ["Elite Soccer","1994","Elite","Elite","Soccer", 'NA'],
	        ["Emmitt Smith Football","November 1, 1995","Bitmasters","JVC","Football", 'NA'],
	        ["Equinox","March 5, 1994","Software Creations","Sony Imagesoft","Action/Puzzle", 'NA'],
	        ["ESPN Baseball Tonight","May 1, 1994","Park Place Productions","Sony Imagesoft","Baseball", 'NA'],
	        ["ESPN National Hockey Night","December 1, 1994","Sony Imagesoft","Sony Imagesoft","Hockey", 'NA'],
	        ["ESPN Speed World","November 30, 1994","Sony Imagesoft","Sony Imagesoft","Racing", 'NA'],
	        ["ESPN Sunday Night NFL","November 10, 1994","Absolute Entertainment","Sony Imagesoft","Football", 'NA'],
	        ["Extra Innings","March 20, 1992","Sony Imagesoft","Sony Imagesoft","Baseball", 'NA'],
	        ["Eye of the Beholder","April 1, 1994","Capcom","Capcom","Role-playing", 'NA'],
	        ["F-Zero","August 23, 1991","Nintendo","Nintendo","Racing", 'NA'],
	        ["F1 Pole Position","September 3, 1993","Human Entertainment","Ubisoft","Racing", 'NA'],
	        ["F1 ROC: Race of Champions","September 1, 1992","SETA","SETA","Racing", 'NA'],
	        ["F1 ROC II: Race of Champions","July 1, 1994","SETA","SETA","Racing", 'NA'],
	        ["Faceball 2000","September 30, 1992","Xanth Software","Bullet-Proof Software","First-Person Shooter", 'NA'],
	        ["Family Dog","June 23, 1993","Imagineering","Malibu Games","Platformer", 'NA'],
	        ["Family Feud","September 13, 1993","Imagineering","GameTek","Game Show", 'NA'],
	        ["Fatal Fury: King of Fighters","April 1, 1993","Nova Co., Ltd","Takara","Fighting", 'NA'],
	        ["Fatal Fury 2","April 1, 1994","Nova Co., Ltd","Takara","Fighting", 'NA'],
	        ["Fatal Fury Special","April 1, 1995","Takara","Takara","Fighting", 'NA'],
	        ["FIFA International Soccer","May 1, 1994","Extended Play Productions","EA Sports","Soccer", 'NA'],
	        ["FIFA Soccer 96","July 1, 1995","Extended Play Productions / Probe Entertainment","EA Sports","Soccer", 'NA'],
	        ["FIFA 97: Gold Edition","September 6, 1996","Electronic Arts","EA Sports","Soccer", 'NA'],
	        ["Fighter's History","August 1, 1994","Data East","Data East","Fighting", 'NA'],
	        ["Final Fantasy II","November 23, 1991","Square","Square","Role-playing", 'NA'],
	        ["Final Fantasy III","October 20, 1994","Square","Square","Role-playing", 'NA'],
	        ["Final Fantasy Mystic Quest","October 5, 1992","Square","Square","Role-playing", 'NA'],
	        ["Final Fight","September 1, 1991","Capcom","Capcom","Beat 'Em Up", 'NA'],
	        ["Final Fight 2","August 15, 1993","Capcom","Capcom","Beat 'Em Up", 'NA'],
	        ["Final Fight 3","January 1, 1996","Capcom","Capcom","Beat 'Em Up", 'NA'],
	        ["Final Fight Guy","June 1, 1994","Capcom","Capcom","Beat 'Em Up", 'NA'],
	        ["Firepower 2000","November 13, 1992","Sales Curve Interactive","Sunsoft","Scrolling Shooter", 'NA'],
	        ["Firestriker","October 20, 1994","Axes Art Amuse","DTMC","Action", 'NA'],
	        ["First Samurai","July 2, 1993","Kemco","Kemco","Platformer", 'NA'],
	        ["Flashback: The Quest for Identity","February 1, 1994","Delphine Software International","U.S. Gold","Cinematic Platformer", 'NA'],
	        ["The Flintstones","February 1, 1995","Ocean Software","Ocean Software","Platformer", 'NA'],
	        ["The Flintstones: The Treasure of Sierra Madrock","March 1, 1994","Taito","Taito","Platformer", 'NA'],
	        ["Football Fury","October 1, 1993","American Sammy","American Sammy","Football", 'NA'],
	        ["Foreman For Real","September 1, 1995","Software Creations","Acclaim Entertainment","Boxing", 'NA'],
	        ["Frank Thomas' Big Hurt Baseball","November 1, 1995","Iguana Entertainment","Acclaim Entertainment","Baseball", 'NA'],
	        ["Frantic Flea","April 1, 1996","Haus Teknikka","GameTek","Action", 'NA'],
	        ["Frogger","October 6, 1998","Morning Star Multimedia","Majesco Entertainment","Action", 'NA'],
	        ["Full Throttle: All-American Racing","January 1, 1995","Gremlin Interactive","GameTek","Racing", 'NA'],
	        ["Fun 'n Games","August 1, 1994","Leland Interactive Media","Tradewest","Compilation", 'NA'],
	        ["Gemfire","December 1, 1992","Koei","Koei","Turn-based Strategy", 'NA'],
	        ["Genghis Khan II: Clan of the Gray Wolf","December 1, 1993","Koei","Koei","Strategy", 'NA'],
	        ["George Foreman's KO Boxing","September 1, 1992","Beam Software","Acclaim Entertainment","Boxing", 'NA'],
	        ["Ghoul Patrol","November 1, 1994","LucasArts","JVC","Action", 'NA'],
	        ["Goal!","December 7, 1992","Tose","Jaleco","Soccer", 'NA'],
	        ["Gods","December 31, 1992","Bitmap Brothers","Mindscape","Action/Platformer", 'NA'],
	        ["Goof Troop","July 11, 1993","Capcom","Capcom","Action/Puzzle", 'NA'],
	        ["GP-1","October 29, 1993","Atlus","Atlus","Racing", 'NA'],
	        ["GP-1: Part II","December 1, 1994","Atlus","Atlus","Racing", 'NA'],
	        ["Gradius III","August 23, 1991","Konami","Konami","Scrolling Shooter", 'NA'],
	        ["The Great Circus Mystery Starring Mickey & Minnie","October 16, 1994","Capcom","Capcom","Platformer", 'NA'],
	        ["The Great Waldo Search","June 1, 1993","Radiance Software","THQ","Puzzle", 'NA'],
	        ["GunForce","November 27, 1992","Bits Studios","Irem","Run and Gun", 'NA'],
	        ["Hagane: The Final Conflict","June 1, 1995","Red Entertainment","Hudson Soft","Action", 'NA'],
	        ["Hal's Hole in One Golf","September 15, 1991","HAL Laboratory","HAL Laboratory","Golf", 'NA'],
	        ["HammerLock Wrestling","October 1, 1994","Jaleco","Jaleco","Wrestling", 'NA'],
	        ["Hardball III","June 1, 1994","Accolade","Accolade","Baseball", 'NA'],
	        ["Harley's Humongous Adventure","February 1, 1993","Visual Concepts","Hi Tech Expressions","Platformer", 'NA'],
	        ["Harvest Moon","June 25, 1997","Pack-In-Video","Natsume","Simulation", 'NA'],
	        ["Head-On Soccer","September 1, 1995","U.S. Gold","U.S. Gold","Soccer", 'NA'],
	        ["Hit the Ice","February 1, 1993","Taito","Taito","Hockey", 'NA'],
	        ["Home Alone","December 30, 1991","Altron","THQ","Action", 'NA'],
	        ["Home Alone 2: Lost in New York","October 1, 1992","Imagineering","THQ","Action", 'NA'],
	        ["Home Improvement: Power Tool Pursuit!","November 1, 1994","Absolute Entertainment","Absolute Entertainment","Action/Platformer", 'NA'],
	        ["Hook","October 13, 1992","Ukiyotei","Sony Imagesoft","Platformer", 'NA'],
	        ["The Hunt for Red October","January 1, 1993","Riedel Software Productions","Hi Tech Expressions","Side scroller", 'NA'],
	        ["Hurricanes","December 31, 1994","Probe Entertainment","U.S. Gold","Platformer", 'NA'],
	        ["Hyper V-Ball","June 1, 1994","Video System","Video System","Volleyball", 'NA'],
	        ["Hyper Zone","September 1, 1991","HAL Laboratory","HAL Laboratory","Rail Shooter", 'NA'],
	        ["The Ignition Factor","January 1, 1995","Jaleco","Jaleco","Action", 'NA'],
	        ["Illusion of Gaia","September 1, 1994","Quintet","Nintendo","Role-playing", 'NA'],
	        ["Imperium","November 1, 1992","Vic Tokai","Vic Tokai","Scrolling Shooter", 'NA'],
	        ["Incantation","December 1, 1996","Titus Software","Titus Software","Platformer", 'NA'],
	        ["The Incredible Crash Dummies","October 1, 1993","Gray Matter","LJN","Action", 'NA'],
	        ["The Incredible Hulk","August 1, 1994","Probe Entertainment","U.S. Gold","Action", 'NA'],
	        ["Indiana Jones' Greatest Adventures","October 11, 1994","Factor 5","JVC / LucasArts","Action/Platformer", 'NA'],
	        ["Inindo: Way of the Ninja","March 1, 1993","Koei","Koei","Role-playing", 'NA'],
	        ["Inspector Gadget","December 1, 1993","Hudson Soft","Hudson Soft","Platformer", 'NA'],
	        ["International Superstar Soccer","June 1, 1995","Konami","Konami","Soccer", 'NA'],
	        ["International Superstar Soccer Deluxe","November 1, 1995","Konami","Konami","Soccer", 'NA'],
	        ["International Tennis Tour","November 1, 1993","Loriciel","Taito","Tennis", 'NA'],
	        ["The Irem Skins Game","October 1, 1992","Irem","Irem","Golf", 'NA'],
	        ["The Itchy & Scratchy Game","March 1, 1995","Bits Studios","Acclaim Entertainment","Action", 'NA'],
	        ["Izzy's Quest for the Olympic Rings","November 1, 1995","Alexandria","U.S. Gold","Action/Platformer", 'NA'],
	        ["J.R.R. Tolkien's The Lord of the Rings, Vol. I","October 1994","Interplay Entertainment","Interplay Entertainment","Adventure", 'NA'],
	        ["Jack Nicklaus Golf","May 15, 1992","Tradewest","Tradewest","Golf", 'NA'],
	        ["James Bond Jr.","October 1, 1992","Gray Matter","THQ","Action/Platformer", 'NA'],
	        ["Jammit","November 1994","GTE Interactive Media","GTE Interactive Media","Basketball", 'NA'],
	        ["Jeopardy!","December 1, 1992","Imagineering","GameTek","Game Show", 'NA'],
	        ["Jeopardy! Deluxe Edition","June 1994","GameTek","GameTek","Game Show", 'NA'],
	        ["Jeopardy! Sports Edition","May 1994","GameTek","GameTek","Game Show", 'NA'],
	        ["The Jetsons: Invasion of the Planet Pirates","June 1994","Sting Entertainment","Taito","Platformer", 'NA'],
	        ["Jim Lee's WildC.A.T.S: Covert Action Teams","November 1995","Beam Software","Playmates","Beat 'Em Up", 'NA'],
	        ["Jim Power: The Lost Dimension in 3-D","December 10, 1993","Loriciel","Electro Brain","Action", 'NA'],
	        ["Jimmy Connors Pro Tennis Tour","December 1, 1992","Blue Byte","Ubisoft","Tennis", 'NA'],
	        ["Jimmy Houston's Bass Tournament U.S.A.","November 1, 1995","American Sammy","American Sammy","Fishing", 'NA'],
	        ["Joe & Mac","January 7, 1992","Data East","Data East","Platformer", 'NA'],
	        ["Joe & Mac 2: Lost in the Tropics","April 1994","Data East","Data East","Platformer", 'NA'],
	        ["John Madden Football","November 1, 1991","Park Place Productions","EA Sports","Football", 'NA'],
	        ["John Madden Football '93","November 21, 1992","EA Canada","EA Sports","Football", 'NA'],
	        ["Judge Dredd","January 1995","Probe Entertainment","Acclaim Entertainment","Action", 'NA'],
	        ["The Jungle Book","April 15, 1994","Eurocom","Virgin Interactive","Platformer", 'NA'],
	        ["Jungle Strike","1995","Gremlin Interactive","Electronic Arts","Shoot 'Em Up", 'NA'],
	        ["Jurassic Park","November 30, 1993","Ocean Software","Ocean Software","Adventure", 'NA'],
	        ["Jurassic Park 2: The Chaos Continues","January 1995","Ocean Software","Ocean Software","Action", 'NA'],
	        ["Justice League Task Force","June 1995","Blizzard Entertainment / Sunsoft","Acclaim Entertainment","Fighting", 'NA'],
	        ["Ka-Blooey","August 31, 1992","Mirrorsoft","Kemco","Puzzle", 'NA'],
	        ["Kawasaki Caribbean Challenge","June 1993","Park Place Productions","GameTek","Racing", 'NA'],
	        ["Kawasaki Superbike Challenge","December 1995","Domark","Time Warner Interactive","Racing", 'NA'],
	        ["Ken Griffey Jr. Presents Major League Baseball","March 23, 1994","Software Creations","Nintendo","Baseball", 'NA'],
	        ["Ken Griffey Jr.'s Winning Run","June 10, 1996","Rare","Nintendo","Baseball", 'NA'],
	        ["Kendo Rage","October 1993","SETA","SETA","Action", 'NA'],
	        ["Kid Klown in Crazy Chase","September 1994","Kemco","Kemco","Action", 'NA'],
	        ["Killer Instinct","August 30, 1995","Rare","Nintendo","Fighting", 'NA'],
	        ["King Arthur & the Knights of Justice","May 1995","Manley & Associates","Enix","Action-adventure", 'NA'],
	        ["King Arthur's World","September 4, 1994","Argonaut Games","Jaleco","Side-scrolling Strategy", 'NA'],
	        ["The King of Dragons","1994","Capcom","Capcom","Beat 'Em Up", 'NA'],
	        ["King of the Monsters","October 1, 1992","Takara","Takara","Fighting", 'NA'],
	        ["King of the Monsters 2","June 1, 1994","Takara","Takara","Fighting", 'NA'],
	        ["Kirby Super Star","September 20, 1996","HAL Laboratory","Nintendo","Platformer", 'NA'],
	        ["Kirby's Avalanche","April 25, 1995","Compile/HAL Laboratory","Nintendo","Puzzle", 'NA'],
	        ["Kirby's Dream Course","February 28, 1995","HAL Laboratory","Nintendo","Golf", 'NA'],
	        ["Kirby's Dream Land 3","November 27, 1997","HAL Laboratory","Nintendo","Platformer", 'NA'],
	        ["Knights of the Round","April 1994","Capcom","Capcom","Beat 'Em Up", 'NA'],
	        ["Krusty's Super Fun House","June 1, 1992","Audiogenic","Acclaim Entertainment","Puzzle", 'NA'],
	        ["Kyle Petty's No Fear Racing","April 1995","Leland Interactive Media","Williams Entertainment","Racing", 'NA'],
	        ["Lagoon","February 1, 1992","Zoom Inc.","Kemco","Role-playing", 'NA'],
	        ["Lamborghini American Challenge","1993","Titus Software","Titus Software","Racing", 'NA'],
	        ["Last Action Hero","October 1993","Bits Studios","Sony Imagesoft","Beat 'Em Up", 'NA'],
	        ["The Lawnmower Man","November 8, 1993","Sales Curve Interactive","THQ","Action", 'NA'],
	        ["Legend","April 1994","Arcade Zone","Seika Corporaption","Beat 'Em Up", 'NA'],
	        ["The Legend of the Mystical Ninja","June 30, 1992","Konami","Konami","Action", 'NA'],
	        ["The Legend of Zelda: A Link to the Past","April 13, 1992","Nintendo","Nintendo","Action Role-playing", 'NA'],
	        ["Lemmings","March 1, 1992","Psygnosis","Sunsoft","Puzzle", 'NA'],
	        ["Lemmings 2: The Tribes","November 1, 1994","Psygnosis","Psygnosis","Puzzle", 'NA'],
	        ["Lester the Unlikely","January 1994","Visual Concepts","DTMC","Action/Platformer", 'NA'],
	        ["Lethal Enforcers","January 1994","Konami","Konami","Light Gun Shooter", 'NA'],
	        ["Lethal Weapon","December 31, 1992","Ocean Software","Ocean Software","Action", 'NA'],
	        ["Liberty or Death","March 18, 1994","Koei","Koei","Turn-based Strategy", 'NA'],
	        ["The Lion King","December 8, 1994","Westwood Studios","Virgin Interactive","Platformer", 'NA'],
	        ["Lock On","October 1993","Vic Tokai","Vic Tokai","Jet Flight Simulation", 'NA'],
	        ["Looney Tunes B-Ball","February 1995","Sunsoft","Sunsoft","Basketball", 'NA'],
	        ["The Lost Vikings","April 29, 1993","Silicon & Synapse","Interplay Entertainment","Action/Puzzle", 'NA'],
	        ["The Lost Vikings 2","May 4, 1997","Blizzard Entertainment","Interplay Entertainment","Action/Puzzle", 'NA'],
	        ["Lufia & the Fortress of Doom","December 1993","Neverland","Taito","Role-playing", 'NA'],
	        ["Lufia II: Rise of the Sinistrals","August 31, 1996","Neverland","Natsume","Role-playing", 'NA'],
	        ["M.A.C.S. Basic Rifle Marksmanship","1993","Sculptured Software","","Shooting Simulator", 'NA'],
	        ["Madden NFL '94","November 19, 1993","Visual Concepts","Electronic Arts","Football", 'NA'],
	        ["Madden NFL '95","November 1994","Visual Concepts","Electronic Arts","Football", 'NA'],
	        ["Madden NFL '96","November 10, 1995","Tiburon Entertainment","Electronic Arts","Football", 'NA'],
	        ["Madden NFL 97","October 1996","Tiburon Entertainment","Electronic Arts","Football", 'NA'],
	        ["Madden NFL 98","November 2, 1997","Electronic Arts","THQ","Football", 'NA'],
	        ["Magic Boy","August 1996","Empire Software","JVC","Platformer", 'NA'],
	        ["Magic Sword","August 14, 1992","Minakuchi Engineering","Capcom","Action/Platformer", 'NA'],
	        ["The Magical Quest Starring Mickey Mouse","December 23, 1992","Capcom","Capcom","Platformer", 'NA'],
	        ["Mario is Missing!","June 1993","The Software Toolworks","The Software Toolworks","Educational", 'NA'],
	        ["Mario Paint","August 1, 1992","Nintendo","Nintendo","Art Tool", 'NA'],
	        ["Mario's Early Years! Fun with Letters","September 1994","The Software Toolworks","The Software Toolworks","Educational", 'NA'],
	        ["Mario's Early Years! Fun with Numbers","October 1994","The Software Toolworks","The Software Toolworks","Educational", 'NA'],
	        ["Mario's Early Years! Preschool Fun","November 1994","The Software Toolworks","The Software Toolworks","Educational", 'NA'],
	        ["Mario's Time Machine","December 1993","The Software Toolworks","The Software Toolworks","Educational", 'NA'],
	        ["Mark Davis' The Fishing Master","April 1996","Natsume","Natsume","Fishing", 'NA'],
	        ["Marvel Super Heroes: War of the Gems","November 1996","Capcom","Capcom","Action", 'NA'],
	        ["Mary Shelley's Frankenstein","November 1994","Bits Studios","Sony Imagesoft","Action", 'NA'],
	        ["The Mask","October 1995","Black Pearl Software","Black Pearl Software","Action", 'NA'],
	        ["Math Blaster: Episode 1","October 1994","Western Technologies","Davidson & Associates","Educational", 'NA'],
	        ["Maui Mallard in Cold Shadow", "November 1996", "Eurocom Entertainment Software","Nintendo","Action", 'NA'],
	        ["Mecarobot Golf","September 1993","Toho","Toho","Golf", 'NA'],
	        ["MechWarrior","May 1993","Beam Software","Activision","Simulation", 'NA'],
	        ["MechWarrior 3050","October 1995","Tiburon Entertainment","Activision","Simulation", 'NA'],
	        ["Mega Man 7","September 30, 1995","Capcom","Capcom","Platformer", 'NA'],
	        ["Mega Man Soccer","April 2, 1994","Sun L","Capcom","Soccer", 'NA'],
	        ["Mega Man X","January 19, 1994","Capcom","Capcom","Platformer", 'NA'],
	        ["Mega Man X2","January 6, 1995","Capcom","Capcom","Platformer", 'NA'],
	        ["Mega Man X3","January 4, 1996","Minakuchi Engineering","Capcom","Platformer", 'NA'],
	        ["Metal Combat: Falcon's Revenge","December 1993","Intelligent Systems","Nintendo","Light Gun Shooter", 'NA'],
	        ["Metal Marines","December 1993","Namco","Namco","Real-time Strategy", 'NA'],
	        ["Metal Morph","December 1994","Origin Systems","FCI","Action", 'NA'],
	        ["Metal Warriors","April 1995","LucasArts","Konami","Action", 'NA'],
	        ["Michael Andretti's Indy Car Challenge","September 1994","Genki","Bullet-Proof Software","Racing", 'NA'],
	        ["Michael Jordan: Chaos in the Windy City","November 21, 1994","Electronic Arts","Electronic Arts","Platformer", 'NA'],
	        ["Mickey Mania: The Timeless Adventures of Mickey Mouse","October 1, 1994","Traveller's Tales","Sony Imagesoft","Platformer", 'NA'],
	        ["Mickey's Ultimate Challenge","February 1994","Designer Software","Hi Tech Expressions","Puzzle", 'NA'],
	        ["Micro Machines","December 1994","Codemasters","Ocean Software","Racing", 'NA'],
	        ["Might and Magic III: Isles of Terra","January 1995","Iguana Entertainment","FCI","Role-playing", 'NA'],
	        ["Mighty Morphin Power Rangers","1995","Natsume","Bandai","Beat 'Em Up", 'NA'],
	        ["Mighty Morphin Power Rangers: The Movie","1995","Bandai","Bandai","Beat 'Em Up", 'NA'],
	        ["Mighty Morphin Power Rangers Fighting Edition","1995","Bandai","Bandai","Fighting", 'NA'],
	        ["Miracle Piano","December 31, 1991","The Software Toolworks","The Software Toolworks","Educational", 'NA'],
	        ["MLBPA Baseball","March 1994","Visual Concepts","EA Sports","Baseball", 'NA'],
	        ["Mohawk & Headphone Jack","1996","Black Pearl Software","THQ","Action", 'NA'],
	        ["Monopoly","September 1, 1992","Sculptured Software","Parker Brothers","Board game", 'NA'],
	        ["Mortal Kombat","September 13, 1993","Sculptured Software","Acclaim Entertainment","Fighting", 'NA'],
	        ["Mortal Kombat II","September 9, 1994","Sculptured Software","Acclaim Entertainment","Fighting", 'NA'],
	        ["Mortal Kombat 3","October 13, 1995","Sculptured Software","Williams Entertainment","Fighting", 'NA'],
	        ["Mountain Bike Rally","November 1994","Radical Entertainment","Life Fitness Entertainment","Racing", 'NA'],
	        ["Mr. Do!","December 1, 1996","C-Lab","Black Pearl Software","Action", 'NA'],
	        ["Mr. Nutz","1994","Ocean Software","Ocean Software","Platformer", 'NA'],
	        ["Ms. Pac-Man","September 1, 1996","Digital Eclipse Software","Williams Entertainment","Action", 'NA'],
	        ["Musya","December 31, 1992","Jorudan","SETA","Action", 'NA'],
	        ["Natsume Championship Wrestling","June 1994","Natsume","Natsume","Wrestling", 'NA'],
	        ["NBA All-Star Challenge","December 31, 1992","Beam Software","LJN","Basketball", 'NA'],
	        ["NBA Give 'n Go","1995","Konami","Konami","Basketball", 'NA'],
	        ["NBA Hangtime","1996","Funcom","Midway Games","Basketball", 'NA'],
	        ["NBA Jam","1994","Iguana Entertainment","Acclaim Entertainment","Basketball", 'NA'],
	        ["NBA Jam Tournament Edition","1995","Iguana Entertainment","Acclaim Entertainment","Basketball", 'NA'],
	        ["NBA Live 95","1994","Electronic Arts","EA Sports","Basketball", 'NA'],
	        ["NBA Live 96","1995","Electronic Arts","EA Sports","Basketball", 'NA'],
	        ["NBA Live 97","1996","Electronic Arts","EA Sports","Basketball", 'NA'],
	        ["NBA Live 98","June 17, 1997","EA Sports / Tiertex","THQ","Basketball", 'NA'],
	        ["NBA Showdown","October 1993","Electronic Arts","EA Sports","Basketball", 'NA'],
	        ["NCAA Basketball","October 1, 1992","Sculptured Software","HAL Laboratory / Nintendo","Basketball", 'NA'],
	        ["NCAA Final Four Basketball","February 1995","Bitmasters","Mindscape","Basketball", 'NA'],
	        ["NCAA Football","October 1994","The Software Toolworks","Mindscape","Football", 'NA'],
	        ["Newman/Haas IndyCar featuring Nigel Mansell","1994","Gremlin Interactive","Acclaim Entertainment","Racing", 'NA'],
	        ["NFL Football","1993","Park Place Productions","Konami","Football", 'NA'],
	        ["NFL Quarterback Club","1994","Iguana Entertainment","LJN","Football", 'NA'],
	        ["NFL Quarterback Club 96","1995","Iguana Entertainment","Acclaim Entertainment","Football", 'NA'],
	        ["NHL 94","1993","Electronic Arts","EA Sports","Hockey", 'NA'],
	        ["NHL 95","1994","Visual Concepts / High Score Productions","EA Sports","Hockey", 'NA'],
	        ["NHL 96","October 26, 1995","High Score Productions / Tiburon Entertainment","EA Sports","Hockey", 'NA'],
	        ["NHL 97","October 31, 1996","Black Pearl Software","EA Sports","Hockey", 'NA'],
	        ["NHL 98","October 23, 1997","THQ","EA Sports","Hockey", 'NA'],
	        ["NHL Stanley Cup","1993","Sculptured Software","Nintendo","Hockey", 'NA'],
	        ["NHLPA Hockey '93","December 31, 1992","Electronic Arts","EA Sports","Hockey", 'NA'],
	        ["Nickelodeon Guts","November 1994","Viacom New Media","Viacom New Media","Game Show", 'NA'],
	        ["Nigel Mansell's World Championship Racing","1993","Gremlin Interactive","GameTek","Racing", 'NA'],
	        ["Ninja Gaiden Trilogy","August 10, 1995","Tecmo","Tecmo","Platformer", 'NA'],
	        ["Ninja Warriors","1994","Natsume","Taito","Beat 'Em Up", 'NA'],
	        ["No Escape","November 1994","Bits Studios","Sony Imagesoft","Action", 'NA'],
	        ["Nobunaga's Ambition","December 1993","Koei","Koei","Strategy", 'NA'],
	        ["Nobunaga's Ambition: Lord of Darkness","1994","Koei","Koei","Strategy", 'NA'],
	        ["Nolan Ryan's Baseball","February 28, 1992","Romstar","Romstar","Baseball", 'NA'],
	        ["Nosferatu","October 1995","SETA","SETA","Action", 'NA'],
	        ["Obitus","September 1994","Psygnosis","Bullet-Proof Software","Action Role-playing", 'NA'],
	        ["Ogre Battle: March of the Black Queen","May 15, 1995","Quest","Enix","Real-time Tactics", 'NA'],
	        ["Olympic Summer Games","1996","Black Pearl Software / Tiertex","U.S. Gold","Olympics", 'NA'],
	        ["On the Ball","November 1, 1992","Taito","Taito","Action", 'NA'],
	        ["Operation Europe: Path to Victory","June 1994","Koei","Koei","Turn-based Strategy", 'NA'],
	        ["Operation Logic Bomb","1993","Jaleco","Jaleco","Action", 'NA'],
	        ["Operation Thunderbolt","October 1994","Aisystem Tokyo","Taito","Light Gun Shooter", 'NA'],
	        ["Oscar","1996","Flair Software","Titus Software","Platformer", 'NA'],
	        ["Out of This World","November 1, 1992","Delphine Software International","Interplay Entertainment","Cinematic Platformer", 'NA'],
	        ["Out to Lunch","1993","Mindscape","Mindscape","Platformer", 'NA'],
	        ["Outlander","1993","Mindscape","Mindscape","Action, Racing", 'NA'],
	        ["P.T.O.: Pacific Theater of Operations","September 1993","Koei","Koei","Turn-based Strategy", 'NA'],
	        ["P.T.O. II: Pacific Theater of Operations","December 1995","Koei","Koei","Turn-based Strategy", 'NA'],
	        ["Pac-Attack","1993","Namco","Namco","Puzzle", 'NA'],
	        ["Pac-In-Time","1995","Kalisto Entertainment","Namco","Platformer", 'NA'],
	        ["Pac-Man 2: The New Adventures","1994","Namco","Namco","Adventure", 'NA'],
	        ["Packy and Marlon","June 1995","Wave Quest","Raya Systems","Educational Platformer", 'NA'],
	        ["The Pagemaster","1994","Probe Entertainment","Fox Interactive","Platformer", 'NA'],
	        ["Paladin's Quest","October 1993","Asmik Ace Entertainment","Enix","Role-playing", 'NA'],
	        ["Paperboy 2","November 1, 1991","Tengen","Mindscape","Action", 'NA'],
	        ["The Peace Keepers","March 1994","Jaleco","Jaleco","Beat 'Em Up", 'NA'],
	        ["PGA European Tour","1996","Electronic Arts","Black Pearl Software","Golf", 'NA'],
	        ["PGA Tour 96","January 31, 1996","Electronic Arts","Black Pearl Software","Golf", 'NA'],
	        ["PGA Tour Golf","March 1, 1992","Polygames","EA Sports","Golf", 'NA'],
	        ["Phalanx","October 1, 1992","Kemco","Kemco","Scrolling Shooter", 'NA'],
	        ["Phantom 2040","1995","Viacom New Media","Viacom New Media","Action", 'NA'],
	        ["Pieces","December 1994","Hori Electric","Atlus","Puzzle", 'NA'],
	        ["Pilotwings","August 23, 1991","Nintendo","Nintendo","Simulation", 'NA'],
	        ["Pinball Dreams","1994","Coconuts Japan","GameTek","Pinball", 'NA'],
	        ["Pinball Fantasies","1995","21st Century Entertainment","GameTek","Pinball", 'NA'],
	        ["Pink Goes to Hollywood","1993","Altron","TecMagik","Action", 'NA'],
	        ["Pirates of Dark Water","1994","Sunsoft","Sunsoft","Beat 'Em Up", 'NA'],
	        ["Pitfall: The Mayan Adventure","1994","Redline Games","Activision","Action", 'NA'],
	        ["Pit-Fighter","March 1, 1992","THQ","THQ","Fighting", 'NA'],
	        ["Plok","1993","Software Creations","Tradewest","Platformer", 'NA'],
	        ["Pocky & Rocky","1993","Natsume","Natsume","Adventure", 'NA'],
	        ["Pocky & Rocky 2","1994","Natsume","Natsume","Adventure", 'NA'],
	        ["Populous","September 30, 1991","Bullfrog Productions","Acclaim Entertainment","Real-time Strategy", 'NA'],
	        ["Porky Pig's Haunted Holiday","1995","Phoenix Interactive Entertainment","Acclaim Entertainment/Sunsoft","Platformer", 'NA'],
	        ["Power Instinct","December 1994","Atlus","Atlus","Fighting", 'NA'],
	        ["Power Moves","January 1993","Kaneko","Kaneko","Fighting", 'NA'],
	        ["Power Piggs of the Dark Age","1996","Radical Entertainment","Titus Software","Platformer", 'NA'],
	        ["Power Rangers Zeo: Battle Racers","1996","Bandai","Bandai","Vehicular Combat", 'NA'],
	        ["Prehistorik Man","1996","Titus Software","Titus Software","Platformer", 'NA'],
	        ["Primal Rage","1995","Bitmasters","Time Warner Interactive","Fighting", 'NA'],
	        ["Prince of Persia","November 1, 1992","Arsys Software","Konami","Cinematic Platformer", 'NA'],
	        ["Prince of Persia 2: The Shadow and the Flame","October 1, 1996","Titus Software","Titus Software","Cinematic Platformer", 'NA'],
	        ["Pro Quarterback","December 31, 1992","Tradewest","Tradewest","Football", 'NA'],
	        ["Pro Sport Hockey","February 1994","Tose","Jaleco","Hockey", 'NA'],
	        ["Pushover","December 31, 1992","Red Rat Software","Ocean Software","Puzzle", 'NA'],
	        ["Q*bert 3","October 1, 1992","Realtime Associates","NTVIC","Action/Puzzle", 'NA'],
	        ["Race Drivin'","October 1, 1992","Argonaut Games","THQ","Racing", 'NA'],
	        ["Radical Rex","1994","Laser Beam Entertainment","Activision","Platformer", 'NA'],
	        ["Raiden Trad","April 1, 1992","Seibu Kaihatsu/Toei Company/Micronics","Electro Brain","Scrolling Shooter", 'NA'],
	        ["Rampart","August 1, 1992","Bitmasters","Electronic Arts","Strategy", 'NA'],
	        ["Ranma ½: Hard Battle","1993","Atelier Double","DTMC","Fighting", 'NA'],
	        ["Rap Jam: Volume One","1995","Motown Software","Mandingo Entertainment","Basketball", 'NA'],
	        ["Realm","1996","Titus Software","Titus Software","Action", 'NA'],
	        ["Redline F-1 Racer","1993","Absolute Entertainment","Absolute Entertainment","Racing", 'NA'],
	        ["Relief Pitcher","1994","Left Field Productions","Left Field Productions","Baseball", 'NA'],
	        ["The Ren & Stimpy Show: Buckaroo$!","1993","Imagineering","THQ","Platformer", 'NA'],
	        ["The Ren & Stimpy Show: Fire Dogs","1994","Argonaut Games","THQ","Action", 'NA'],
	        ["The Ren & Stimpy Show: Time Warp","1994","Sculptured Software","THQ","Adventure", 'NA'],
	        ["The Ren & Stimpy Show: Veediots!","1993","Gray Matter","THQ","Platformer", 'NA'],
	        ["Revolution X","1995","Software Creations","Acclaim Entertainment","Rail Shooter", 'NA'],
	        ["Rex Ronan: Experimental Surgeon","1994","Sculptured Software","Raya Systems","Educational Action", 'NA'],
	        ["Riddick Bowe Boxing","1994","Malibu Interactive","Extreme Entertainment Group","Boxing, Fighting", 'NA'],
	        ["Rise of the Phoenix","1995","Koei","Koei","Turn-based Strategy", 'NA'],
	        ["Rise of the Robots","1994","Probe Entertainment","Acclaim Entertainment","Fighting", 'NA'],
	        ["Rival Turf!","December 23, 1992","Jaleco","Jaleco","Beat 'Em Up", 'NA'],
	        ["Road Riot 4WD","November 1, 1992","Equilibrium","THQ","Racing", 'NA'],
	        ["Road Runner's Death Valley Rally","November 1, 1992","ICOM Simulations","Sunsoft","Platformer", 'NA'],
	        ["RoboCop 3","September 1, 1992","Ocean Software","Ocean Software","Action", 'NA'],
	        ["RoboCop Versus The Terminator","1993","Virgin Interactive","Virgin Interactive","Action", 'NA'],
	        ["Robotrek","1994","Quintet","Enix","Role-playing", 'NA'],
	        ["Rock n' Roll Racing","June 4, 1993","Silicon & Synapse","Interplay Entertainment","Racing", 'NA'],
	        ["The Rocketeer","May 1, 1992","NovaLogic","IGS","Action", 'NA'],
	        ["Rocko's Modern Life: Spunky's Dangerous Day","1994","Viacom New Media","Viacom New Media","Adventure", 'NA'],
	        ["Rocky Rodent","1993","Irem","Irem","Platformer", 'NA'],
	        ["Roger Clemens' MVP Baseball","September 12, 1992","Sculptured Software","LJN","Baseball", 'NA'],
	        ["Romance of the Three Kingdoms II","May 1, 1992","Koei","Koei","Turn-based strategy", 'NA'],
	        ["Romance of the Three Kingdoms III: Dragon of Destiny","December 1, 1993","Koei","Koei","Turn-based strategy", 'NA'],
	        ["Romance of the Three Kingdoms IV: Wall of Fire","July 1, 1995","Koei","Koei","Turn-based strategy", 'NA'],
	        ["RPM Racing","November 1, 1991","Silicon & Synapse","Interplay Entertainment","Racing", 'NA'],
	        ["R-Type III: The Third Lightning","August 2, 1994","Irem","Jaleco","Scrolling Shooter", 'NA'],
	        ["Run Saber","June 8, 1993","Hori Electric","Atlus","Action/Platformer", 'NA'],
	        ["Samurai Shodown","September 14, 1994","Takara","Takara","Fighting", 'NA'],
	        ["Saturday Night Slam Masters","1994","Capcom","Capcom","Wrestling", 'NA'],
	        ["Scooby-Doo Mystery","1995","Argonaut Software","Acclaim Entertainment/Sunsoft","Adventure", 'NA'],
	        ["SeaQuest DSV","1995","Sculptured Software","Malibu Games","Strategy, Scrolling Shooter", 'NA'],
	        ["Secret of Evermore","October 1, 1995","Square","Square","Role-playing", 'NA'],
	        ["Secret of Mana","October 3, 1993","Square","Square","Role-playing", 'NA'],
	        ["Secret of the Stars","1995","Tecmo","Tecmo","Role-playing", 'NA'],
	        ["Shadowrun","May 1, 1993","Beam Software","Data East","Action Role-playing", 'NA'],
	        ["Shanghai II: Dragon's Eye","1993","Hot-B","Activision","Board Game", 'NA'],
	        ["Shaq Fu","October 28, 1994","Delphine Software International","Electronic Arts","Fighting", 'NA'],
	        ["Shien's Revenge","1994","Almanic","Vic Tokai","Rail Shooter", 'NA'],
	        ["Side Pocket","1993","Iguana Entertainment","Data East","Billiards", 'NA'],
	        ["SimAnt","1993","Tomcat System","Maxis Software","Simulation", 'NA'],
	        ["SimCity","August 23, 1991","Nintendo/Maxis","Nintendo","Simulation", 'NA'],
	        ["SimCity 2000","1996","THQ","Black Pearl Software","Simulation", 'NA'],
	        ["SimEarth","1993","Tomcat System","FCI","Simulation", 'NA'],
	        ["The Simpsons: Bart's Nightmare","October 12, 1992","Sculptured Software","Acclaim Entertainment","Action/Compilation", 'NA'],
	        ["Sink or Swim","January 31, 1996","Zeppelin Games","Titus Software","Puzzle, Platformer", 'NA'],
	        ["Sküljagger: Revolt of the Westicans","October 1, 1992","Realtime Associates","American Softworks","Action/Platformer", 'NA'],
	        ["Skyblazer","March 16, 1994","Ukiyotei","Sony Imagesoft","Platformer", 'NA'],
	        ["Smart Ball","March 1, 1992","Game Freak, System Sacom","Sony Imagesoft","Action", 'NA'],
	        ["Snow White: Happily Ever After","1994","Imagitec Design","American Softworks","Platformer", 'NA'],
	        ["Soldiers of Fortune","1993","Bitmap Brothers","Spectrum Holobyte","Action", 'NA'],
	        ["Sonic Blast Man","1993","I.T.L / Zuntata","Taito","Beat 'Em Up", 'NA'],
	        ["Sonic Blast Man II","1994","Taito / I.T.L","Taito","Beat 'Em Up", 'NA'],
	        ["SOS","1994","Human Entertainment","Vic Tokai","Action", 'NA'],
	        ["Soul Blazer","November 27, 1992","Quintet","Enix","Action Role-playing", 'NA'],
	        ["Space Ace","1994","Entertainment International","Absolute Entertainment","Action", 'NA'],
	        ["Space Football: One on One","June 1, 1992","Bits Studios","Triffix","Sports", 'NA'],
	        ["Space Invaders","November 1, 1997","Taito","Nintendo","Action", 'NA'],
	        ["Space Megaforce","October 30, 1992","Compile","Toho","Scrolling Shooter", 'NA'],
	        ["Spanky's Quest","July 1, 1992","Natsume","Natsume","Action", 'NA'],
	        ["Sparkster","October 1, 1994","Konami","Konami","Action/Platformer", 'NA'],
	        ["Spectre","1994","Synergistic Software","Cybersoft","First-Person Shooter", 'NA'],
	        ["Speed Racer in My Most Dangerous Adventures","1994","Radical Entertainment","Accolade","Racing", 'NA'],
	        ["Speedy Gonzales: Los Gatos Bandidos","1995","Sunsoft","Sunsoft","Platformer", 'NA'],
	        ["Spellcraft: Aspects of Valor","1993","Asciiware","Broderbund","Adventure", 'NA'],
	        ["Spider-Man: The Animated Series","1995","Western Technologies","LJN","Action", 'NA'],
	        ["Spider-Man and Venom: Maximum Carnage","September 16, 1994","Software Creations","LJN","Beat 'Em Up", 'NA'],
	        ["Spider-Man and the X-Men in Arcade's Revenge","November 1, 1992","Software Creations","LJN","Action/Platformer", 'NA'],
	        ["Spindizzy Worlds","1993","ASCII Entertainment","ASCII Entertainment","Puzzle", 'NA'],
	        ["The Sporting News: Power Baseball","1995","Now Production","Hudson Soft","Baseball", 'NA'],
	        ["Sports Illustrated: Championship Football & Baseball","1994","Malibu Games","Malibu Games","Sports Compilation", 'NA'],
	        ["Star Fox","March 23, 1993","Nintendo/Argonaut Games","Nintendo","3D Shooter", 'NA'],
	        ["Star Trek: Deep Space Nine: The Crossroads of Time","1995","Novotrade","Playmates","Action, Adventure", 'NA'],
	        ["Star Trek: Starfleet Academy Starship Bridge Simulator","1994","Paramount Interactive","Interplay Entertainment","Simulation", 'NA'],
	        ["Star Trek: The Next Generation: Future's Past","1994","Spectrum Holobyte","Spectrum Holobyte","Adventure", 'NA'],
	        ["Stargate","1995","Probe Entertainment","Acclaim Entertainment","Action", 'NA'],
	        ["Steel Talons","1993","Panoramic","Left Field Productions","Multidirectional Shooter", 'NA'],
	        ["Sterling Sharpe: End 2 End","1995","Tose","Jaleco","Football", 'NA'],
	        ["Stone Protectors","1994","Eurocom","Kemco","Beat 'Em Up", 'NA'],
	        ["Street Combat","1993","Opus Corporation","Irem","Fighting", 'NA'],
	        ["Street Fighter Alpha 2","November 1, 1996","Capcom","Nintendo","Fighting", 'NA'],
	        ["Street Fighter II: The World Warrior","July 1, 1992","Capcom","Capcom","Fighting", 'NA'],
	        ["Street Fighter II Turbo: Hyper Fighting","August 13, 1993","Capcom","Capcom","Fighting", 'NA'],
	        ["Street Hockey '95","1994","GTE Interactive Media","GTE Interactive Media","Hockey", 'NA'],
	        ["Street Racer","1994","Vivid Image","Ubisoft","Racing", 'NA'],
	        ["Strike Gunner S.T.G","October 15, 1992","Athena","NTVIC","Scrolling Shooter", 'NA'],
	        ["Stunt Race FX","October 10, 1994","Nintendo/Argonaut Games","Nintendo","Racing", 'NA'],
	        ["Sunset Riders","June 8, 1993","Konami","Konami","Run and Gun", 'NA'],
	        ["Super Adventure Island","April 1, 1992","Produce!","Hudson Soft","Platformer", 'NA'],
	        ["Super Adventure Island II","May 10, 1995","Make Software","Hudson Soft","Adventure", 'NA'],
	        ["The Super Aquatic Games Starring the Aquabats","1993","Millennium Interactive","Seika Corporation","Sports", 'NA'],
	        ["Super Baseball 2020","1993","Monolith Corporation","Tradewest","Baseball", 'NA'],
	        ["Super Baseball Simulator 1.000","December 1, 1991","Culture Brain","Culture Brain","Baseball", 'NA'],
	        ["Super Bases Loaded","September 30, 1991","Tose","Jaleco","Baseball", 'NA'],
	        ["Super Bases Loaded 2","1994","Tose","Jaleco","Baseball", 'NA'],
	        ["Super Bases Loaded 3: License to Steal","1995","Tose","Jaleco","Baseball", 'NA'],
	        ["Super Batter Up","October 1, 1992","Namco","Namco","Baseball", 'NA'],
	        ["Super Battleship","1993","World Builders Synergistic","Mindscape","Strategy", 'NA'],
	        ["Garry Kitchen's Super Battletank: War in the Gulf","June 1, 1992","Imagineering","Absolute Entertainment","Simulation", 'NA'],
	        ["Super Battletank 2","January 11, 1994","Absolute Entertainment","Absolute Entertainment","Simulation", 'NA'],
	        ["Super Black Bass","1993","Starfish","Hot-B","Fishing", 'NA'],
	        ["Super Bomberman","May 10, 1993","Hudson Soft","Hudson Soft","Action/Puzzle", 'NA'],
	        ["Super Bomberman 2","December 12, 1994","Hudson Soft","Hudson Soft","Action/Puzzle", 'NA'],
	        ["Super Bonk","1994","Red Company","Hudson Soft","Platformer", 'NA'],
	        ["Super Bowling","September 1992","Athena","Technōs Japan","Bowling", 'NA'],
	        ["Super Buster Bros.","October 1992","Capcom","Capcom","Action", 'NA'],
	        ["Super Caesars Palace","August 8, 1993","Illusion Softworks","Virgin Interactive","Gambling", 'NA'],
	        ["Super Castlevania IV","December 4, 1991","Konami","Konami","Action/Platformer", 'NA'],
	        ["Super Chase H.Q.","1993","Taito","Taito","Racing", 'NA'],
	        ["Super Conflict","1993","Vic Tokai","Vic Tokai","Turn-based Strategy", 'NA'],
	        ["Super Double Dragon","October 1992","Technōs Japan","Tradewest","Beat 'Em Up", 'NA'],
	        ["Super Ghouls 'n Ghosts","November 28, 1991","Capcom","Capcom","Platformer", 'NA'],
	        ["Super Goal! 2","1994","Tose","Jaleco","Soccer", 'NA'],
	        ["Super Godzilla","1994","Toho","Toho","Action", 'NA'],
	        ["Super High Impact","1993","Iguana Entertainment","Acclaim Entertainment","Football", 'NA'],
	        ["Super James Pond","1993","American Softworks","American Softworks","Platformer", 'NA'],
	        ["Super Mario All-Stars","August 1, 1993","Nintendo","Nintendo","Platformer", 'NA'],
	        ["Super Mario All-Stars + Super Mario World","1994","Nintendo","Nintendo","Platformer", 'NA'],
	        ["Super Mario Kart","September 1, 1992","Nintendo","Nintendo","Racing", 'NA'],
	        ["Super Mario RPG: Legend of the Seven Stars","May 13, 1996","Square","Nintendo","Role-playing", 'NA'],
	        ["Super Mario World","August 13, 1991","Nintendo","Nintendo","Platformer", 'NA'],
	        ["Super Mario World 2: Yoshi's Island","October 4, 1995","Nintendo","Nintendo","Platformer", 'NA'],
	        ["Super Metroid","April 18, 1994","Nintendo","Nintendo","Action/Platformer", 'NA'],
	        ["Super Ninja Boy","1993","Culture Brain","Culture Brain","Action Role-playing", 'NA'],
	        ["Super Nova","1993","Taito","Taito","Scrolling Shooter", 'NA'],
	        ["Super Off Road","December 1, 1991","Software Creations","Tradewest","Racing", 'NA'],
	        ["Super Off Road: The Baja","July 2, 1993","Software Creations","Tradewest","Racing", 'NA'],
	        ["Super Pinball: Behind the Mask","1994","KaZe / Meldac","Nintendo","Pinball", 'NA'],
	        ["Super Play Action Football","1992","Tose","Nintendo","Football", 'NA'],
	        ["Super Punch-Out!!","September 14, 1994","Nintendo","Nintendo","Boxing", 'NA'],
	        ["Super Putty","1993","System 3","U.S. Gold","Platformer", 'NA'],
	        ["Super R.B.I. Baseball","1995","Gray Matter","Time Warner Interactive","Baseball", 'NA'],
	        ["Super R-Type","September 1, 1991","Irem","Irem","Scrolling Shooter", 'NA'],
	        ["Super Scope 6","February 1992","Nintendo","Nintendo","Light Gun Shooter", 'NA'],
	        ["Super Slam Dunk","1993","Virgin Interactive","Virgin Interactive","Basketball", 'NA'],
	        ["Super Slap Shot","1993","Ringler Studios","Virgin Interactive","Hockey", 'NA'],
	        ["Super Smash TV","1992","Beam Software","Acclaim Entertainment","Action", 'NA'],
	        ["Super Soccer","May 1992","Human Entertainment","Nintendo","Soccer", 'NA'],
	        ["Super Soccer Champ","June 1992","Taito","Taito","Soccer", 'NA'],
	        ["Super Solitaire","1994","Extreme Entertainment Group","Extreme Entertainment Group","Card Game", 'NA'],
	        ["Super Star Wars","June 1, 1992","Sculptured Software","JVC / LucasArts","Platformer/Run and Gun", 'NA'],
	        ["Super Star Wars: The Empire Strikes Back","June 1, 1993","Sculptured Software","JVC / LucasArts","Platformer/Run and Gun", 'NA'],
	        ["Super Star Wars: Return of the Jedi","June 22, 1994","Sculptured Software","JVC / LucasArts","Platformer/Run and Gun", 'NA'],
	        ["Super Street Fighter II: The New Challengers","July 18, 1994","Capcom","Capcom","Fighting", 'NA'],
	        ["Super Strike Eagle","1993","MicroProse","MicroProse","Combat Flight Simulator", 'NA'],
	        ["Super Tennis","November 2, 1991","Tokyo Shoseki","Nintendo","Tennis", 'NA'],
	        ["Super Troll Islands","1994","Kemco","American Softworks","Action", 'NA'],
	        ["Super Turrican","1993","Factor 5","Seika Corporation","Action", 'NA'],
	        ["Super Turrican 2","1995","Factor 5","Ocean Software","Action", 'NA'],
	        ["Super Valis IV","February 1993","Telenet Japan","Atlus","Action", 'NA'],
	        ["Super Widget","1993","Atlus","Atlus","Platformer", 'NA'],
	        ["Suzuka 8 Hours","1994","Namco","Namco","Racing", 'NA'],
	        ["SWAT Kats: The Radical Squadron","August 21, 1995","AIM","Hudson Soft","Platformer", 'NA'],
	        ["Syndicate","1995","Bullfrog Productions","Ocean Software","Real-time Tactics", 'NA'],
	        ["T2: The Arcade Game","1994","Probe Entertainment","LJN","Action", 'NA'],
	        ["Taz-Mania","1993","Visual Concepts","Sunsoft","Racing", 'NA'],
	        ["Tecmo Super Baseball","1994","Tecmo","Tecmo","Baseball", 'NA'],
	        ["Tecmo Super Bowl","1993","Tecmo","Tecmo","Football", 'NA'],
	        ["Tecmo Super Bowl II: Special Edition","1995","Tecmo","Tecmo","Football", 'NA'],
	        ["Tecmo Super Bowl III: Final Edition","1995","Tecmo","Tecmo","Football", 'NA'],
	        ["Tecmo Super NBA Basketball","1993","Tecmo","Tecmo","Basketball", 'NA'],
	        ["Teenage Mutant Ninja Turtles IV: Turtles in Time","August 15, 1992","Konami","Konami","Beat 'Em Up", 'NA'],
	        ["Teenage Mutant Ninja Turtles: Tournament Fighters","1993","Konami","Konami","Fighting", 'NA'],
	        ["The Terminator","1993","Mindscape","Mindscape","Action", 'NA'],
	        ["Terminator 2: Judgment Day","1993","Bits Studios","LJN","Action", 'NA'],
	        ["Tetris & Dr. Mario","December 30, 1994","Tose","Nintendo","Puzzle", 'NA'],
	        ["Tetris 2","1994","Bullet-Proof Software","Nintendo","Puzzle", 'NA'],
	        ["Tetris Attack","August 4, 1996","Intelligent Systems","Nintendo","Puzzle", 'NA'],
	        ["Thomas the Tank Engine & Friends","August 2, 1993","Software Creations","THQ","Action, Adventure", 'NA'],
	        ["Thunder Spirits","June 1992","Technosoft","Seika Corporation","Scrolling Shooter", 'NA'],
	        ["The Tick","1994","Software Creations","Fox Interactive","Beat 'Em Up", 'NA'],
	        ["Time Slip","1993","Sales Curve Interactive","Vic Tokai","Action", 'NA'],
	        ["Time Trax","1994","Malibu Games","Malibu Games","Action", 'NA'],
	        ["Timecop","1995","Cryo Interactive","JVC","Action", 'NA'],
	        ["Timon & Pumbaa's Jungle Games","November 30, 1997","Tiertex Design Studios","THQ","Compilation", 'NA'],
	        ["Tin Star","1994","Software Creations","Nintendo","Rail Shooter, Light Gun Shooter", 'NA'],
	        ["Tiny Toon Adventures: Buster Busts Loose","1993","Konami","Konami","Platformer", 'NA'],
	        ["Tiny Toon Adventures: Wacky Sports Challenge","1994","Konami","Konami","Sports", 'NA'],
	        ["TKO Super Championship Boxing","October 1992","Sting Entertainment","Sofel","Boxing", 'NA'],
	        ["TNN Bass Tournament of Champions","1994","American Softworks","American Softworks","Fishing", 'NA'],
	        ["Todd McFarlane's Spawn: The Video Game","1995","Ukiyotei","Acclaim Entertainment","Beat 'Em Up", 'NA'],
	        ["Tom and Jerry","1993","Riedel Software Productions","Hi Tech Expressions","Platformer", 'NA'],
	        ["Tommy Moe's Winter Extreme: Skiing & Snowboarding","1994","Loriciel","Electro Brain","Skiing/Snowboarding", 'NA'],
	        ["Tony Meola's Sidekicks Soccer","1993","Sculptured Software","Electro Brain","Soccer", 'NA'],
	        ["Top Gear","April 16, 1992","Gremlin Interactive","Kemco","Racing", 'NA'],
	        ["Top Gear 2","August 8, 1993","Gremlin Interactive","Kemco","Racing", 'NA'],
	        ["Top Gear 3000","1995","Gremlin Interactive","Kemco","Racing", 'NA'],
	        ["Total Carnage","1993","Black Pearl Software","Malibu Games","Action", 'NA'],
	        ["Toy Story","December 31, 1995","Traveller's Tales","Disney Interactive","Platformer", 'NA'],
	        ["Toys","1993","Absolute Entertainment","Absolute Entertainment","Action", 'NA'],
	        ["Troddlers","1993","Atod","Seika Corporation","Puzzle", 'NA'],
	        ["Troy Aikman NFL Football","1994","Tradewest","Tradewest","Football", 'NA'],
	        ["True Golf: Wicked 18","1993","T&E Software","Bullet-Proof Software","Golf", 'NA'],
	        ["True Golf Classics: Pebble Beach Golf Links","April 1992","T&E Software","T&E Software","Golf", 'NA'],
	        ["True Golf Classics: Waialae Country Club","November 30, 1991","T&E Software","T&E Software","Golf", 'NA'],
	        ["True Lies","1995","Beam Software","LJN","Action", 'NA'],
	        ["Tuff E Nuff","1993","Jaleco","Jaleco","Fighting", 'NA'],
	        ["Turn and Burn: No-Fly Zone","1994","Absolute Entertainment","Absolute Entertainment","Jet Flight Simulator", 'NA'],
	        ["The Twisted Tales of Spike McFang","1994","Red Entertainment","Bullet-Proof Software","Action Role-playing", 'NA'],
	        ["U.N. Squadron","September 9, 1991","Capcom","Capcom","Scrolling Shooter", 'NA'],
	        ["Ultima: Runes of Virtue II","1994","Origin Systems","FCI","Role-playing", 'NA'],
	        ["Ultima VI: The False Prophet","1994","Infinity Co., Ltd","FCI","Role-playing", 'NA'],
	        ["Ultima VII: The Black Gate","1994","Origin Systems","FCI","Role-playing", 'NA'],
	        ["Ultimate Fighter","1994","Culture Brain","Culture Brain","Fighting", 'NA'],
	        ["Ultimate Mortal Kombat 3","June 26, 1996","Avalanche Software","Williams Entertainment","Fighting", 'NA'],
	        ["Ultraman: Towards the Future","October 19, 1991","Bandai","Bandai","Fighting", 'NA'],
	        ["Uncharted Waters","1993","Koei","Koei","Simulation, Role-playing", 'NA'],
	        ["Uncharted Waters: New Horizons","1994","Koei","Koei","Simulation, Role-playing", 'NA'],
	        ["Uniracers","June 1, 1994","DMA Design","Nintendo","Racing", 'NA'],
	        ["Untouchables","1994","Ocean Software","Ocean Software","Action", 'NA'],
	        ["Urban Strike","1995","Granite Bay Software","Black Pearl Software","Shoot 'Em Up", 'NA'],
	        ["Utopia: The Creation of a Nation","1993","Jaleco","Jaleco","Real-time Strategy", 'NA'],
	        ["Vegas Stakes","1993","HAL Laboratory","Nintendo","Gambling", 'NA'],
	        ["Venom/Spider-Man: Separation Anxiety","1995","Software Creations","Acclaim Entertainment","Beat 'Em Up", 'NA'],
	        ["Virtual Bart","September 26, 1994","Sculptured Software","Acclaim Entertainment","Action/Compilation", 'NA'],
	        ["Vortex","1994","Argonaut Games","Electro Brain","3D Shooter", 'NA'],
	        ["War 2410","December 1995","Advanced Productions","Advanced Productions","Turn-based Strategy", 'NA'],
	        ["War 3010: The Revolution","October 1, 1996","Advanced Productions","Advanced Productions","Turn-based strategy", 'NA'],
	        ["Wario's Woods","December 10, 1994","Nintendo","Nintendo","Puzzle", 'NA'],
	        ["Warlock","March 1995","Realtime Associates","LJN","Action", 'NA'],
	        ["WarpSpeed","December 1992","Accolade","Accolade","Space Flight Simulator", 'NA'],
	        ["Wayne Gretzky and the NHLPA All-Stars","December 1995","Time Warner Interactive","Time Warner Interactive","Sports (ice hockey)", 'NA'],
	        ["Wayne's World","April 1993","Gray Matter","THQ","Action", 'NA'],
	        ["WCW SuperBrawl Wrestling","November 1994","Beam Software","FCI","Wrestling", 'NA'],
	        ["Weaponlord","September 1995","Visual Concepts","Namco","Fighting", 'NA'],
	        ["We're Back! A Dinosaur's Story","November 1993","Visual Concepts","Hi Tech Expressions","Action", 'NA'],
	        ["Wheel of Fortune: Featuring Vanna White","September 1992","Imagitec Design","GameTek","Game Show", 'NA'],
	        ["Wheel of Fortune Deluxe!","April 1994","Imagitec Design","GameTek","Game Show", 'NA'],
	        ["Where in the World Is Carmen Sandiego?","June 1993","EA Canada","Hi Tech Expressions","Educational strategy", 'NA'],
	        ["Where in Time is Carmen Sandiego?","May 1993","EA Canada","Hi Tech Expressions","Educational strategy", 'NA'],
	        ["Whizz","November 1, 1996","Flair Software","Titus Software","Action", 'NA'],
	        ["Wild Guns","July 4, 1995","Natsume","Natsume","Cabal Shooter", 'NA'],
	        ["WildSnake","September 1994","Manley & Associates","Spectrum HoloByte","Puzzle", 'NA'],
	        ["Williams Arcade's Greatest Hits","October 31, 1996","Digital Eclipse Software","Williams Entertainment","Arcade Compilation", 'NA'],
	        ["Wing Commander","March 1992","Origin Systems","Mindscape","Space flight simulator", 'NA'],
	        ["Wing Commander: The Secret Missions","September 1993","Origin Systems","Mindscape","Space flight simulator", 'NA'],
	        ["Wings 2: Aces High","October 1992","Namco","Namco","Flight sim", 'NA'],
	        ["Winter Olympic Games: Lillehammer '94","February 1994","U.S. Gold","U.S. Gold","Sports Compilation", 'NA'],
	        ["The Wizard of Oz","October 5, 1993","SETA","SETA","Adventure (movie based)", 'NA'],
	        ["Wizardry V: Heart of the Maelstrom","April 1994","ASCII Entertainment","Capcom","Role-Playing", 'NA'],
	        ["Wolfchild","June 1993","Core Design","Virgin Interactive","Platformer", 'NA'],
	        ["Wolfenstein 3D","March 1994","Imagineer","Imagineer","First-person shooter", 'NA'],
	        ["Wolverine: Adamantium Rage","November 1994","Bits Studios","LJN","Action", 'NA'],
	        ["Wordtris","November 1992","Bullet-Proof Software","Spectrum HoloByte","Puzzle", 'NA'],
	        ["World Cup USA '94","June 1994","U.S. Gold","U.S. Gold","Soccer", 'NA'],
	        ["World Heroes","September 1993","Sunsoft","Sunsoft","Fighting", 'NA'],
	        ["World Heroes 2","September 1994","Saurus Co., Ltd","Takara","Fighting", 'NA'],
	        ["World League Soccer","April 1992","ANCO","Mindscape","Soccer", 'NA'],
	        ["World Soccer '94: Road to Glory","December 1, 1993","Rage Software","Elite","Soccer", 'NA'],
	        ["WWF RAW","November 1994","Sculptured Software","LJN","Wrestling", 'NA'],
	        ["WWF Royal Rumble","June 8, 1993","Sculptured Software","LJN","Wrestling", 'NA'],
	        ["WWF Super WrestleMania","February 12, 1992","Sculptured Software","LJN","Wrestling", 'NA'],
	        ["WWF WrestleMania: The Arcade Game","November 1995","Iguana Entertainment","Acclaim Entertainment","Wrestling", 'NA'],
	        ["Xardion","April 1992","Asmik Ace Entertainment","Asmik Ace Entertainment","Action, side scroller, platformer", 'NA'],
	        ["X-Kaliber 2097","February 1994","Toshiba EMI","Activision","Platformer", 'NA'],
	        ["X-Men: Mutant Apocalypse","November 1994","Capcom","Capcom","Action", 'NA'],
	        ["X-Zone","November 1992","Kemco","Kemco","Rail Shooter", 'NA'],
	        ["Yoshi's Cookie","April 1, 1993","Bullet-Proof Software","Bullet-Proof Software","Puzzle", 'NA'],
	        ["Yoshi's Safari","September 3, 1993","Nintendo","Nintendo","Light Gun Shooter", 'NA'],
	        ["Young Merlin","March 18, 1994","Westwood Studios","Virgin Interactive","Role-Playing", 'NA'],
	        ["Ys III: Wanderers from Ys","January 10, 1992","Tonkin House","American Sammy","Action Role-Playing", 'NA'],
	        ["Zero the Kamikaze Squirrel","November 1, 1994","Iguana Entertainment","Sunsoft","Platformer", 'NA'],
	        ["Zombies Ate My Neighbors","September 24, 1993","LucasArts","Konami","Action", 'NA'],
	        ["Zool","June 1, 1993","Gremlin Interactive","GameTek","Platformer", 'NA'],
	        ["Zoop","September 15, 1995","Hookstone Productions","Viacom New Media","Puzzle", 'NA'],
	        ["Super 3D Noah's Ark","1994","Wisdom Tree","Wisdom Tree","First Person Shooter", 'NA'],
        ];

        foreach ($games as $game) {
        	DB::table('games')->insert([
        		'platform' => 'SNES',
        		'name' => $game[0],
        		'release_date' => $game[1],
				'developer' => $game[2],
				'publisher' => $game[3],
				'genre' => $game[4],
				'region' => $game[5],
				'created_at' => \Carbon\Carbon::now(),
				'updated_at' => \Carbon\Carbon::now(),
        	]);
        }
    }
}
